INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY) 
VALUES('CONTRIBUTOR','Contributor-owned work',SYSDATE,0);
INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY)
VALUES('US_GOVT','U.S. Government work',SYSDATE,0);
INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY) 
VALUES('UK_GOVT','U.K. Government work',SYSDATE,0);
INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY) 
VALUES('NGO','Non-Governmental Organization work',SYSDATE,0);
INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY) 
VALUES('OTHER_GOVT','Other Government work',SYSDATE,0);
INSERT INTO OWNERSHIP_TYPES(TYPE_CD,TYPE_NAME,CREATED_DATE,CREATED_BY) 
VALUES('COMPANY_INSTITUTION','Company/institution owned work',SYSDATE,0);


INSERT INTO SUB_OWNERSHIP_TYPES(SUB_TYPE_CD,SUB_TYPE_NAME,OWNERSHIP_TYPE_CD,CREATED_DATE,CREATED_BY) 
VALUES('ALL_AUTHORS_NIH_EMPL','All authors are NIH employees','US_GOVT',SYSDATE,0);
INSERT INTO SUB_OWNERSHIP_TYPES(SUB_TYPE_CD,SUB_TYPE_NAME,OWNERSHIP_TYPE_CD,CREATED_DATE,CREATED_BY) 
VALUES('NOT_ALL_AUTHORS_NIH_EMPL','Not all authors are NIH employees','US_GOVT',SYSDATE,0);
INSERT INTO SUB_OWNERSHIP_TYPES(SUB_TYPE_CD,SUB_TYPE_NAME,OWNERSHIP_TYPE_CD,CREATED_DATE,CREATED_BY) 
VALUES('ALL_AUTHORS_US_GOVT_EMPL','All other authors are U.S. Government employees','US_GOVT',SYSDATE,0);
INSERT INTO SUB_OWNERSHIP_TYPES(SUB_TYPE_CD,SUB_TYPE_NAME,OWNERSHIP_TYPE_CD,CREATED_DATE,CREATED_BY) 
VALUES('NOT_ALL_AUTHORS_US_GOVT_EMPL','Not all other authors are U.S. Government employees','US_GOVT',SYSDATE,0);



INSERT INTO LICENSE_REJECTION_REASONS(REASON_CD,REASON_TEXT,REASON_DESCRIPTION,CREATED_DATE,CREATED_BY)
VALUES('UDNLASS','Uploaded doc is not LA','Uploaded document is not the license agreement sent by the system',SYSDATE,0);
INSERT INTO LICENSE_REJECTION_REASONS(REASON_CD,REASON_TEXT,REASON_DESCRIPTION,CREATED_DATE,CREATED_BY) 
VALUES('SMILA','sign missing in LA','Signature is missing in license agreement',SYSDATE,0);
INSERT INTO LICENSE_REJECTION_REASONS(REASON_CD,REASON_TEXT,REASON_DESCRIPTION,CREATED_DATE,CREATED_BY) 
VALUES('OIM','Ownership info mismatch','Ownership Information mismatched',SYSDATE,0);
INSERT INTO LICENSE_REJECTION_REASONS(REASON_CD,REASON_TEXT,REASON_DESCRIPTION,CREATED_DATE,CREATED_BY)
VALUES('NDM','NIH doc missing','NIH document is missing',SYSDATE,0);
