package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdditionalPermissions generated by hbm2java
 */
public class AdditionalPermissions implements java.io.Serializable {

	private AdditionalPermissionsId id;
	private Roles roles;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private Permissions permissions;
	private Date createdDate;
	private Date updatedDate;

	public AdditionalPermissions() {
	}

	public AdditionalPermissions(AdditionalPermissionsId id,
			AuthorProfile authorProfile, Permissions permissions) {
		this.id = id;
		this.authorProfile = authorProfile;
		this.permissions = permissions;
	}

	public AdditionalPermissions(AdditionalPermissionsId id, Roles roles,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			AuthorProfile authorProfile, Permissions permissions,
			Date createdDate, Date updatedDate) {
		this.id = id;
		this.roles = roles;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.permissions = permissions;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public AdditionalPermissionsId getId() {
		return this.id;
	}

	public void setId(AdditionalPermissionsId id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
