package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuditDetails generated by hbm2java
 */
public class AuditDetails implements java.io.Serializable {

	private AuditDetailsId id;
	private Users usersByCreatedBy;
	private Users usersByUserId;

	public AuditDetails() {
	}

	public AuditDetails(AuditDetailsId id) {
		this.id = id;
	}

	public AuditDetails(AuditDetailsId id, Users usersByCreatedBy,
			Users usersByUserId) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUserId = usersByUserId;
	}

	public AuditDetailsId getId() {
		return this.id;
	}

	public void setId(AuditDetailsId id) {
		this.id = id;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

}
