package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthColleagueDetailsId generated by hbm2java
 */
@Embeddable
public class AuthColleagueDetailsId implements java.io.Serializable {
    
    private Integer authColleagueId;
    private String firstName;
    private String lastName;
    private String emailAddr;
    private Integer invitedAuthorId;
    private Integer colleagueUserId;
    private Integer assignedArticleId;
    private Date createdDate;
    private String createdBy;
    private String updatedBy;
    private Date updatedDate;
    
    public AuthColleagueDetailsId() {
    }
    
    public AuthColleagueDetailsId(Integer authColleagueId, String firstName,
            String lastName, String emailAddr, Integer invitedAuthorId,
            Integer colleagueUserId, Integer assignedArticleId,
            Date createdDate, String createdBy, String updatedBy,
            Date updatedDate) {
        this.authColleagueId = authColleagueId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddr = emailAddr;
        this.invitedAuthorId = invitedAuthorId;
        this.colleagueUserId = colleagueUserId;
        this.assignedArticleId = assignedArticleId;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
    }
    
    @Column(name = "AUTH_COLLEAGUE_ID", precision = 22, scale = 0)
    public Integer getAuthColleagueId() {
        return this.authColleagueId;
    }
    
    public void setAuthColleagueId(Integer authColleagueId) {
        this.authColleagueId = authColleagueId;
    }
    
    @Column(name = "FIRST_NAME", length = 50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name = "LAST_NAME", length = 50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column(name = "EMAIL_ADDR", length = 250)
    public String getEmailAddr() {
        return this.emailAddr;
    }
    
    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }
    
    @Column(name = "INVITED_AUTHOR_ID", precision = 22, scale = 0)
    public Integer getInvitedAuthorId() {
        return this.invitedAuthorId;
    }
    
    public void setInvitedAuthorId(Integer invitedAuthorId) {
        this.invitedAuthorId = invitedAuthorId;
    }
    
    @Column(name = "COLLEAGUE_USER_ID", precision = 22, scale = 0)
    public Integer getColleagueUserId() {
        return this.colleagueUserId;
    }
    
    public void setColleagueUserId(Integer colleagueUserId) {
        this.colleagueUserId = colleagueUserId;
    }
    
    @Column(name = "ASSIGNED_ARTICLE_ID", precision = 22, scale = 0)
    public Integer getAssignedArticleId() {
        return this.assignedArticleId;
    }
    
    public void setAssignedArticleId(Integer assignedArticleId) {
        this.assignedArticleId = assignedArticleId;
    }
    
    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name = "CREATED_BY", length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    @Column(name = "UPDATED_BY", length = 100)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AuthColleagueDetailsId))
            return false;
        AuthColleagueDetailsId castOther = (AuthColleagueDetailsId) other;
        
        return ((this.getAuthColleagueId() == castOther.getAuthColleagueId()) || (this
                .getAuthColleagueId() != null
                && castOther.getAuthColleagueId() != null && this
                .getAuthColleagueId().equals(castOther.getAuthColleagueId())))
                && ((this.getFirstName() == castOther.getFirstName()) || (this
                        .getFirstName() != null
                        && castOther.getFirstName() != null && this
                        .getFirstName().equals(castOther.getFirstName())))
                && ((this.getLastName() == castOther.getLastName()) || (this
                        .getLastName() != null
                        && castOther.getLastName() != null && this
                        .getLastName().equals(castOther.getLastName())))
                && ((this.getEmailAddr() == castOther.getEmailAddr()) || (this
                        .getEmailAddr() != null
                        && castOther.getEmailAddr() != null && this
                        .getEmailAddr().equals(castOther.getEmailAddr())))
                && ((this.getInvitedAuthorId() == castOther
                        .getInvitedAuthorId()) || (this.getInvitedAuthorId() != null
                        && castOther.getInvitedAuthorId() != null && this
                        .getInvitedAuthorId().equals(
                                castOther.getInvitedAuthorId())))
                && ((this.getColleagueUserId() == castOther
                        .getColleagueUserId()) || (this.getColleagueUserId() != null
                        && castOther.getColleagueUserId() != null && this
                        .getColleagueUserId().equals(
                                castOther.getColleagueUserId())))
                && ((this.getAssignedArticleId() == castOther
                        .getAssignedArticleId()) || (this
                        .getAssignedArticleId() != null
                        && castOther.getAssignedArticleId() != null && this
                        .getAssignedArticleId().equals(
                                castOther.getAssignedArticleId())))
                && ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
                        .getCreatedDate() != null
                        && castOther.getCreatedDate() != null && this
                        .getCreatedDate().equals(castOther.getCreatedDate())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
                        .getCreatedBy() != null
                        && castOther.getCreatedBy() != null && this
                        .getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this
                        .getUpdatedBy() != null
                        && castOther.getUpdatedBy() != null && this
                        .getUpdatedBy().equals(castOther.getUpdatedBy())))
                && ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this
                        .getUpdatedDate() != null
                        && castOther.getUpdatedDate() != null && this
                        .getUpdatedDate().equals(castOther.getUpdatedDate())));
    }
    
    public int hashCode() {
        int result = 17;
        
        result = 37
                * result
                + (getAuthColleagueId() == null ? 0 : this.getAuthColleagueId()
                        .hashCode());
        result = 37 * result
                + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
        result = 37 * result
                + (getLastName() == null ? 0 : this.getLastName().hashCode());
        result = 37 * result
                + (getEmailAddr() == null ? 0 : this.getEmailAddr().hashCode());
        result = 37
                * result
                + (getInvitedAuthorId() == null ? 0 : this.getInvitedAuthorId()
                        .hashCode());
        result = 37
                * result
                + (getColleagueUserId() == null ? 0 : this.getColleagueUserId()
                        .hashCode());
        result = 37
                * result
                + (getAssignedArticleId() == null ? 0 : this
                        .getAssignedArticleId().hashCode());
        result = 37
                * result
                + (getCreatedDate() == null ? 0 : this.getCreatedDate()
                        .hashCode());
        result = 37 * result
                + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result
                + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
        result = 37
                * result
                + (getUpdatedDate() == null ? 0 : this.getUpdatedDate()
                        .hashCode());
        return result;
    }
    
}
