package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AuthorProfile generated by hbm2java
 */
public class AuthorProfile implements java.io.Serializable {

	private Integer userId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByMergerAccntId;
	private Users usersByUserId;
	private UserSecondaryEmailAddr userSecondaryEmailAddr;
	private String titleCd;
	private String middleName;
	private String suffixCd;
	private String alternativeName;
	private String industryCd;
	private String jobCategoryCd;
	private String optInPromoteFlg;
	private Blob profilePic;
	private Character isAccountActive;
	private Character isAccountVerified;
	private Character cdmUpdstatus;
	private Character profileVisibleFlg;
	private Date createdDate;
	private Date updatedDate;
	private Set<UserAreaOfInterest> userAreaOfInterests = new HashSet<UserAreaOfInterest>(
			0);
	private Set<UserAffiliations> userAffiliationses = new HashSet<UserAffiliations>(
			0);
	private Set<AuthColleagueDetails> authColleagueDetailsesForInvitedAuthorId = new HashSet<AuthColleagueDetails>(
			0);
	private Set<AuthCoauthDetails> authCoauthDetailsesForCoauthUserId = new HashSet<AuthCoauthDetails>(
			0);
	private Set<AdditionalPermissions> additionalPermissionses = new HashSet<AdditionalPermissions>(
			0);
	private Set<UserFunderGrants> userFunderGrantses = new HashSet<UserFunderGrants>(
			0);
	private Set<UserProfileAttribVisible> userProfileAttribVisibles = new HashSet<UserProfileAttribVisible>(
			0);
	private Set<AuthCoauthDetails> authCoauthDetailsesForAuthorId = new HashSet<AuthCoauthDetails>(
			0);
	private Set<UserAlerts> userAlertses = new HashSet<UserAlerts>(0);
	private Set<UserSocietyDetails> userSocietyDetailses = new HashSet<UserSocietyDetails>(
			0);
	private Set<AuthColleagueDetails> authColleagueDetailsesForColleagueUserId = new HashSet<AuthColleagueDetails>(
			0);
	private Set<UserWoaAccounts> userWoaAccountses = new HashSet<UserWoaAccounts>(
			0);
	private Set<UserPreferredJournals> userPreferredJournalses = new HashSet<UserPreferredJournals>(
			0);

	public AuthorProfile() {
	}

	public AuthorProfile(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	public AuthorProfile(Users usersByCreatedBy, Users usersByUpdatedBy,
			Users usersByMergerAccntId, Users usersByUserId,
			UserSecondaryEmailAddr userSecondaryEmailAddr, String titleCd,
			String middleName, String suffixCd, String alternativeName,
			String industryCd, String jobCategoryCd, String optInPromoteFlg,
			Blob profilePic, Character isAccountActive,
			Character isAccountVerified, Character cdmUpdstatus,
			Character profileVisibleFlg, Date createdDate, Date updatedDate,
			Set<UserAreaOfInterest> userAreaOfInterests,
			Set<UserAffiliations> userAffiliationses,
			Set<AuthColleagueDetails> authColleagueDetailsesForInvitedAuthorId,
			Set<AuthCoauthDetails> authCoauthDetailsesForCoauthUserId,
			Set<AdditionalPermissions> additionalPermissionses,
			Set<UserFunderGrants> userFunderGrantses,
			Set<UserProfileAttribVisible> userProfileAttribVisibles,
			Set<AuthCoauthDetails> authCoauthDetailsesForAuthorId,
			Set<UserAlerts> userAlertses,
			Set<UserSocietyDetails> userSocietyDetailses,
			Set<AuthColleagueDetails> authColleagueDetailsesForColleagueUserId,
			Set<UserWoaAccounts> userWoaAccountses,
			Set<UserPreferredJournals> userPreferredJournalses) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByMergerAccntId = usersByMergerAccntId;
		this.usersByUserId = usersByUserId;
		this.userSecondaryEmailAddr = userSecondaryEmailAddr;
		this.titleCd = titleCd;
		this.middleName = middleName;
		this.suffixCd = suffixCd;
		this.alternativeName = alternativeName;
		this.industryCd = industryCd;
		this.jobCategoryCd = jobCategoryCd;
		this.optInPromoteFlg = optInPromoteFlg;
		this.profilePic = profilePic;
		this.isAccountActive = isAccountActive;
		this.isAccountVerified = isAccountVerified;
		this.cdmUpdstatus = cdmUpdstatus;
		this.profileVisibleFlg = profileVisibleFlg;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.userAreaOfInterests = userAreaOfInterests;
		this.userAffiliationses = userAffiliationses;
		this.authColleagueDetailsesForInvitedAuthorId = authColleagueDetailsesForInvitedAuthorId;
		this.authCoauthDetailsesForCoauthUserId = authCoauthDetailsesForCoauthUserId;
		this.additionalPermissionses = additionalPermissionses;
		this.userFunderGrantses = userFunderGrantses;
		this.userProfileAttribVisibles = userProfileAttribVisibles;
		this.authCoauthDetailsesForAuthorId = authCoauthDetailsesForAuthorId;
		this.userAlertses = userAlertses;
		this.userSocietyDetailses = userSocietyDetailses;
		this.authColleagueDetailsesForColleagueUserId = authColleagueDetailsesForColleagueUserId;
		this.userWoaAccountses = userWoaAccountses;
		this.userPreferredJournalses = userPreferredJournalses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Users getUsersByMergerAccntId() {
		return this.usersByMergerAccntId;
	}

	public void setUsersByMergerAccntId(Users usersByMergerAccntId) {
		this.usersByMergerAccntId = usersByMergerAccntId;
	}

	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	public UserSecondaryEmailAddr getUserSecondaryEmailAddr() {
		return this.userSecondaryEmailAddr;
	}

	public void setUserSecondaryEmailAddr(
			UserSecondaryEmailAddr userSecondaryEmailAddr) {
		this.userSecondaryEmailAddr = userSecondaryEmailAddr;
	}

	public String getTitleCd() {
		return this.titleCd;
	}

	public void setTitleCd(String titleCd) {
		this.titleCd = titleCd;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getSuffixCd() {
		return this.suffixCd;
	}

	public void setSuffixCd(String suffixCd) {
		this.suffixCd = suffixCd;
	}

	public String getAlternativeName() {
		return this.alternativeName;
	}

	public void setAlternativeName(String alternativeName) {
		this.alternativeName = alternativeName;
	}

	public String getIndustryCd() {
		return this.industryCd;
	}

	public void setIndustryCd(String industryCd) {
		this.industryCd = industryCd;
	}

	public String getJobCategoryCd() {
		return this.jobCategoryCd;
	}

	public void setJobCategoryCd(String jobCategoryCd) {
		this.jobCategoryCd = jobCategoryCd;
	}

	public String getOptInPromoteFlg() {
		return this.optInPromoteFlg;
	}

	public void setOptInPromoteFlg(String optInPromoteFlg) {
		this.optInPromoteFlg = optInPromoteFlg;
	}

	public Blob getProfilePic() {
		return this.profilePic;
	}

	public void setProfilePic(Blob profilePic) {
		this.profilePic = profilePic;
	}

	public Character getIsAccountActive() {
		return this.isAccountActive;
	}

	public void setIsAccountActive(Character isAccountActive) {
		this.isAccountActive = isAccountActive;
	}

	public Character getIsAccountVerified() {
		return this.isAccountVerified;
	}

	public void setIsAccountVerified(Character isAccountVerified) {
		this.isAccountVerified = isAccountVerified;
	}

	public Character getCdmUpdstatus() {
		return this.cdmUpdstatus;
	}

	public void setCdmUpdstatus(Character cdmUpdstatus) {
		this.cdmUpdstatus = cdmUpdstatus;
	}

	public Character getProfileVisibleFlg() {
		return this.profileVisibleFlg;
	}

	public void setProfileVisibleFlg(Character profileVisibleFlg) {
		this.profileVisibleFlg = profileVisibleFlg;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<UserAreaOfInterest> getUserAreaOfInterests() {
		return this.userAreaOfInterests;
	}

	public void setUserAreaOfInterests(
			Set<UserAreaOfInterest> userAreaOfInterests) {
		this.userAreaOfInterests = userAreaOfInterests;
	}

	public Set<UserAffiliations> getUserAffiliationses() {
		return this.userAffiliationses;
	}

	public void setUserAffiliationses(Set<UserAffiliations> userAffiliationses) {
		this.userAffiliationses = userAffiliationses;
	}

	public Set<AuthColleagueDetails> getAuthColleagueDetailsesForInvitedAuthorId() {
		return this.authColleagueDetailsesForInvitedAuthorId;
	}

	public void setAuthColleagueDetailsesForInvitedAuthorId(
			Set<AuthColleagueDetails> authColleagueDetailsesForInvitedAuthorId) {
		this.authColleagueDetailsesForInvitedAuthorId = authColleagueDetailsesForInvitedAuthorId;
	}

	public Set<AuthCoauthDetails> getAuthCoauthDetailsesForCoauthUserId() {
		return this.authCoauthDetailsesForCoauthUserId;
	}

	public void setAuthCoauthDetailsesForCoauthUserId(
			Set<AuthCoauthDetails> authCoauthDetailsesForCoauthUserId) {
		this.authCoauthDetailsesForCoauthUserId = authCoauthDetailsesForCoauthUserId;
	}

	public Set<AdditionalPermissions> getAdditionalPermissionses() {
		return this.additionalPermissionses;
	}

	public void setAdditionalPermissionses(
			Set<AdditionalPermissions> additionalPermissionses) {
		this.additionalPermissionses = additionalPermissionses;
	}

	public Set<UserFunderGrants> getUserFunderGrantses() {
		return this.userFunderGrantses;
	}

	public void setUserFunderGrantses(Set<UserFunderGrants> userFunderGrantses) {
		this.userFunderGrantses = userFunderGrantses;
	}

	public Set<UserProfileAttribVisible> getUserProfileAttribVisibles() {
		return this.userProfileAttribVisibles;
	}

	public void setUserProfileAttribVisibles(
			Set<UserProfileAttribVisible> userProfileAttribVisibles) {
		this.userProfileAttribVisibles = userProfileAttribVisibles;
	}

	public Set<AuthCoauthDetails> getAuthCoauthDetailsesForAuthorId() {
		return this.authCoauthDetailsesForAuthorId;
	}

	public void setAuthCoauthDetailsesForAuthorId(
			Set<AuthCoauthDetails> authCoauthDetailsesForAuthorId) {
		this.authCoauthDetailsesForAuthorId = authCoauthDetailsesForAuthorId;
	}

	public Set<UserAlerts> getUserAlertses() {
		return this.userAlertses;
	}

	public void setUserAlertses(Set<UserAlerts> userAlertses) {
		this.userAlertses = userAlertses;
	}

	public Set<UserSocietyDetails> getUserSocietyDetailses() {
		return this.userSocietyDetailses;
	}

	public void setUserSocietyDetailses(
			Set<UserSocietyDetails> userSocietyDetailses) {
		this.userSocietyDetailses = userSocietyDetailses;
	}

	public Set<AuthColleagueDetails> getAuthColleagueDetailsesForColleagueUserId() {
		return this.authColleagueDetailsesForColleagueUserId;
	}

	public void setAuthColleagueDetailsesForColleagueUserId(
			Set<AuthColleagueDetails> authColleagueDetailsesForColleagueUserId) {
		this.authColleagueDetailsesForColleagueUserId = authColleagueDetailsesForColleagueUserId;
	}

	public Set<UserWoaAccounts> getUserWoaAccountses() {
		return this.userWoaAccountses;
	}

	public void setUserWoaAccountses(Set<UserWoaAccounts> userWoaAccountses) {
		this.userWoaAccountses = userWoaAccountses;
	}

	public Set<UserPreferredJournals> getUserPreferredJournalses() {
		return this.userPreferredJournalses;
	}

	public void setUserPreferredJournalses(
			Set<UserPreferredJournals> userPreferredJournalses) {
		this.userPreferredJournalses = userPreferredJournalses;
	}

}
