package com.wiley.gr.ace.authorservices.persistence.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AuthColleagueDetails generated by hbm2java
 */
@Entity
@Table(name = "AUTH_COLLEAGUE_DETAILS")
public class AuthColleagueDetails implements java.io.Serializable {

	private AuthColleagueDetailsId id;
	private AuthorProfile authorProfileByColleagueUserId;
	private AuthorProfile authorProfileByInvitedAuthorId;

	public AuthColleagueDetails() {
	}

	public AuthColleagueDetails(AuthColleagueDetailsId id) {
		this.id = id;
	}

	public AuthColleagueDetails(AuthColleagueDetailsId id,
			AuthorProfile authorProfileByColleagueUserId,
			AuthorProfile authorProfileByInvitedAuthorId) {
		this.id = id;
		this.authorProfileByColleagueUserId = authorProfileByColleagueUserId;
		this.authorProfileByInvitedAuthorId = authorProfileByInvitedAuthorId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "authColleagueId", column = @Column(name = "AUTH_COLLEAGUE_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FIRST_NAME", length = 50)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LAST_NAME", length = 50)),
			@AttributeOverride(name = "emailAddr", column = @Column(name = "EMAIL_ADDR", length = 250)),
			@AttributeOverride(name = "invitedAuthorId", column = @Column(name = "INVITED_AUTHOR_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "colleagueUserId", column = @Column(name = "COLLEAGUE_USER_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "assignedArticleId", column = @Column(name = "ASSIGNED_ARTICLE_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", length = 100)),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UPDATED_BY", length = 100)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UPDATED_DATE")) })
	public AuthColleagueDetailsId getId() {
		return this.id;
	}

	public void setId(AuthColleagueDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLLEAGUE_USER_ID", insertable = false, updatable = false)
	public AuthorProfile getAuthorProfileByColleagueUserId() {
		return this.authorProfileByColleagueUserId;
	}

	public void setAuthorProfileByColleagueUserId(
			AuthorProfile authorProfileByColleagueUserId) {
		this.authorProfileByColleagueUserId = authorProfileByColleagueUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVITED_AUTHOR_ID", insertable = false, updatable = false)
	public AuthorProfile getAuthorProfileByInvitedAuthorId() {
		return this.authorProfileByInvitedAuthorId;
	}

	public void setAuthorProfileByInvitedAuthorId(
			AuthorProfile authorProfileByInvitedAuthorId) {
		this.authorProfileByInvitedAuthorId = authorProfileByInvitedAuthorId;
	}

}
