package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Databasechangelog generated by hbm2java
 */
@Entity
@Table(name = "DATABASECHANGELOG")
public class Databasechangelog implements java.io.Serializable {

	private DatabasechangelogId id;
	private Date dateexecuted;
	private String md5sum;
	private String description;
	private String comments;
	private String tag;
	private String liquibase;
	private Integer orderexecuted;
	private String exectype;

	public Databasechangelog() {
	}

	public Databasechangelog(DatabasechangelogId id, Date dateexecuted,
			Integer orderexecuted, String exectype) {
		this.id = id;
		this.dateexecuted = dateexecuted;
		this.orderexecuted = orderexecuted;
		this.exectype = exectype;
	}

	public Databasechangelog(DatabasechangelogId id, Date dateexecuted,
			String md5sum, String description, String comments, String tag,
			String liquibase, Integer orderexecuted, String exectype) {
		this.id = id;
		this.dateexecuted = dateexecuted;
		this.md5sum = md5sum;
		this.description = description;
		this.comments = comments;
		this.tag = tag;
		this.liquibase = liquibase;
		this.orderexecuted = orderexecuted;
		this.exectype = exectype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 63)),
			@AttributeOverride(name = "author", column = @Column(name = "AUTHOR", nullable = false, length = 63)),
			@AttributeOverride(name = "filename", column = @Column(name = "FILENAME", nullable = false, length = 200)) })
	public DatabasechangelogId getId() {
		return this.id;
	}

	public void setId(DatabasechangelogId id) {
		this.id = id;
	}

	@Column(name = "DATEEXECUTED", nullable = false)
	public Date getDateexecuted() {
		return this.dateexecuted;
	}

	public void setDateexecuted(Date dateexecuted) {
		this.dateexecuted = dateexecuted;
	}

	@Column(name = "MD5SUM", length = 35)
	public String getMd5sum() {
		return this.md5sum;
	}

	public void setMd5sum(String md5sum) {
		this.md5sum = md5sum;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "COMMENTS")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "TAG")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "LIQUIBASE", length = 20)
	public String getLiquibase() {
		return this.liquibase;
	}

	public void setLiquibase(String liquibase) {
		this.liquibase = liquibase;
	}

	@Column(name = "ORDEREXECUTED", nullable = false, precision = 10, scale = 0)
	public Integer getOrderexecuted() {
		return this.orderexecuted;
	}

	public void setOrderexecuted(Integer orderexecuted) {
		this.orderexecuted = orderexecuted;
	}

	@Column(name = "EXECTYPE", nullable = false, length = 10)
	public String getExectype() {
		return this.exectype;
	}

	public void setExectype(String exectype) {
		this.exectype = exectype;
	}

}
