package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Journals generated by hbm2java
 */
@Entity
@Table(name = "JOURNALS")
public class Journals implements java.io.Serializable {

	private Integer journalId;
	private String journalpdhid;
	private String jouTitle;
	private String jouSetupStateInAs;
	private String jouTitleDisplayOo;
	private Character discontinued;
	private String salesModel;
	private Character jouInvitedInAs;
	private Character isDisplayedForOoOrder;
	private Character prodTrackPathForJou;
	private Character alrtAssocWithProofsToAuth;
	private Character alrtAssocWithCorrReceived;
	private Character alrtAsscAccepArtPubOnline;
	private Character alrtAsscWithPubErlyVew;
	private Character alrtAsscWithFinOnlineDt;
	private Character alrtAssocArtPublOnlineIss;
	private Character perFreeAccessToArtToCoau;
	private Character allwCoauSeeArtPrdStages;
	private Character perCoauToSubsReviewProofs;
	private Character allowToAddColleagues;
	private Character allowArticlesPrdNonprdPath;
	private Character collecAConfOfIntrstForm;
	private Character dispWrngsAuthMsngLicagrmnt;
	private Character coauthReceiveInvitation;
	private String jouNickname;
	private Character dispOrEmailMrktngToUsr;
	private Character dispOrEmailSurveyToUsr;
	private Date jouInvitedInAsStartDt;
	private Date jouInvitedInAsEndDt;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<UserPreferredJournals> userPreferredJournalses = new HashSet<UserPreferredJournals>(
			0);

	public Journals() {
	}

	public Journals(Integer journalId) {
		this.journalId = journalId;
	}

	public Journals(Integer journalId, String journalpdhid, String jouTitle,
			String jouSetupStateInAs, String jouTitleDisplayOo,
			Character discontinued, String salesModel,
			Character jouInvitedInAs, Character isDisplayedForOoOrder,
			Character prodTrackPathForJou, Character alrtAssocWithProofsToAuth,
			Character alrtAssocWithCorrReceived,
			Character alrtAsscAccepArtPubOnline,
			Character alrtAsscWithPubErlyVew,
			Character alrtAsscWithFinOnlineDt,
			Character alrtAssocArtPublOnlineIss,
			Character perFreeAccessToArtToCoau,
			Character allwCoauSeeArtPrdStages,
			Character perCoauToSubsReviewProofs,
			Character allowToAddColleagues,
			Character allowArticlesPrdNonprdPath,
			Character collecAConfOfIntrstForm,
			Character dispWrngsAuthMsngLicagrmnt,
			Character coauthReceiveInvitation, String jouNickname,
			Character dispOrEmailMrktngToUsr, Character dispOrEmailSurveyToUsr,
			Date jouInvitedInAsStartDt, Date jouInvitedInAsEndDt,
			String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, Set<UserPreferredJournals> userPreferredJournalses) {
		this.journalId = journalId;
		this.journalpdhid = journalpdhid;
		this.jouTitle = jouTitle;
		this.jouSetupStateInAs = jouSetupStateInAs;
		this.jouTitleDisplayOo = jouTitleDisplayOo;
		this.discontinued = discontinued;
		this.salesModel = salesModel;
		this.jouInvitedInAs = jouInvitedInAs;
		this.isDisplayedForOoOrder = isDisplayedForOoOrder;
		this.prodTrackPathForJou = prodTrackPathForJou;
		this.alrtAssocWithProofsToAuth = alrtAssocWithProofsToAuth;
		this.alrtAssocWithCorrReceived = alrtAssocWithCorrReceived;
		this.alrtAsscAccepArtPubOnline = alrtAsscAccepArtPubOnline;
		this.alrtAsscWithPubErlyVew = alrtAsscWithPubErlyVew;
		this.alrtAsscWithFinOnlineDt = alrtAsscWithFinOnlineDt;
		this.alrtAssocArtPublOnlineIss = alrtAssocArtPublOnlineIss;
		this.perFreeAccessToArtToCoau = perFreeAccessToArtToCoau;
		this.allwCoauSeeArtPrdStages = allwCoauSeeArtPrdStages;
		this.perCoauToSubsReviewProofs = perCoauToSubsReviewProofs;
		this.allowToAddColleagues = allowToAddColleagues;
		this.allowArticlesPrdNonprdPath = allowArticlesPrdNonprdPath;
		this.collecAConfOfIntrstForm = collecAConfOfIntrstForm;
		this.dispWrngsAuthMsngLicagrmnt = dispWrngsAuthMsngLicagrmnt;
		this.coauthReceiveInvitation = coauthReceiveInvitation;
		this.jouNickname = jouNickname;
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
		this.jouInvitedInAsStartDt = jouInvitedInAsStartDt;
		this.jouInvitedInAsEndDt = jouInvitedInAsEndDt;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.userPreferredJournalses = userPreferredJournalses;
	}

	@Id
	@Column(name = "JOURNAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getJournalId() {
		return this.journalId;
	}

	public void setJournalId(Integer journalId) {
		this.journalId = journalId;
	}

	@Column(name = "JOURNALPDHID", length = 50)
	public String getJournalpdhid() {
		return this.journalpdhid;
	}

	public void setJournalpdhid(String journalpdhid) {
		this.journalpdhid = journalpdhid;
	}

	@Column(name = "JOU_TITLE", length = 1000)
	public String getJouTitle() {
		return this.jouTitle;
	}

	public void setJouTitle(String jouTitle) {
		this.jouTitle = jouTitle;
	}

	@Column(name = "JOU_SETUP_STATE_IN_AS", length = 250)
	public String getJouSetupStateInAs() {
		return this.jouSetupStateInAs;
	}

	public void setJouSetupStateInAs(String jouSetupStateInAs) {
		this.jouSetupStateInAs = jouSetupStateInAs;
	}

	@Column(name = "JOU_TITLE_DISPLAY_OO", length = 1000)
	public String getJouTitleDisplayOo() {
		return this.jouTitleDisplayOo;
	}

	public void setJouTitleDisplayOo(String jouTitleDisplayOo) {
		this.jouTitleDisplayOo = jouTitleDisplayOo;
	}

	@Column(name = "DISCONTINUED", length = 1)
	public Character getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(Character discontinued) {
		this.discontinued = discontinued;
	}

	@Column(name = "SALES_MODEL", length = 50)
	public String getSalesModel() {
		return this.salesModel;
	}

	public void setSalesModel(String salesModel) {
		this.salesModel = salesModel;
	}

	@Column(name = "JOU_INVITED_IN_AS", length = 1)
	public Character getJouInvitedInAs() {
		return this.jouInvitedInAs;
	}

	public void setJouInvitedInAs(Character jouInvitedInAs) {
		this.jouInvitedInAs = jouInvitedInAs;
	}

	@Column(name = "IS_DISPLAYED_FOR_OO_ORDER", length = 1)
	public Character getIsDisplayedForOoOrder() {
		return this.isDisplayedForOoOrder;
	}

	public void setIsDisplayedForOoOrder(Character isDisplayedForOoOrder) {
		this.isDisplayedForOoOrder = isDisplayedForOoOrder;
	}

	@Column(name = "PROD_TRACK_PATH_FOR_JOU", length = 1)
	public Character getProdTrackPathForJou() {
		return this.prodTrackPathForJou;
	}

	public void setProdTrackPathForJou(Character prodTrackPathForJou) {
		this.prodTrackPathForJou = prodTrackPathForJou;
	}

	@Column(name = "ALRT_ASSOC_WITH_PROOFS_TO_AUTH", length = 1)
	public Character getAlrtAssocWithProofsToAuth() {
		return this.alrtAssocWithProofsToAuth;
	}

	public void setAlrtAssocWithProofsToAuth(Character alrtAssocWithProofsToAuth) {
		this.alrtAssocWithProofsToAuth = alrtAssocWithProofsToAuth;
	}

	@Column(name = "ALRT_ASSOC_WITH_CORR_RECEIVED", length = 1)
	public Character getAlrtAssocWithCorrReceived() {
		return this.alrtAssocWithCorrReceived;
	}

	public void setAlrtAssocWithCorrReceived(Character alrtAssocWithCorrReceived) {
		this.alrtAssocWithCorrReceived = alrtAssocWithCorrReceived;
	}

	@Column(name = "ALRT_ASSC_ACCEP_ART_PUB_ONLINE", length = 1)
	public Character getAlrtAsscAccepArtPubOnline() {
		return this.alrtAsscAccepArtPubOnline;
	}

	public void setAlrtAsscAccepArtPubOnline(Character alrtAsscAccepArtPubOnline) {
		this.alrtAsscAccepArtPubOnline = alrtAsscAccepArtPubOnline;
	}

	@Column(name = "ALRT_ASSC_WITH_PUB_ERLY_VEW", length = 1)
	public Character getAlrtAsscWithPubErlyVew() {
		return this.alrtAsscWithPubErlyVew;
	}

	public void setAlrtAsscWithPubErlyVew(Character alrtAsscWithPubErlyVew) {
		this.alrtAsscWithPubErlyVew = alrtAsscWithPubErlyVew;
	}

	@Column(name = "ALRT_ASSC_WITH_FIN_ONLINE_DT", length = 1)
	public Character getAlrtAsscWithFinOnlineDt() {
		return this.alrtAsscWithFinOnlineDt;
	}

	public void setAlrtAsscWithFinOnlineDt(Character alrtAsscWithFinOnlineDt) {
		this.alrtAsscWithFinOnlineDt = alrtAsscWithFinOnlineDt;
	}

	@Column(name = "ALRT_ASSOC_ART_PUBL_ONLINE_ISS", length = 1)
	public Character getAlrtAssocArtPublOnlineIss() {
		return this.alrtAssocArtPublOnlineIss;
	}

	public void setAlrtAssocArtPublOnlineIss(Character alrtAssocArtPublOnlineIss) {
		this.alrtAssocArtPublOnlineIss = alrtAssocArtPublOnlineIss;
	}

	@Column(name = "PER_FREE_ACCESS_TO_ART_TO_COAU", length = 1)
	public Character getPerFreeAccessToArtToCoau() {
		return this.perFreeAccessToArtToCoau;
	}

	public void setPerFreeAccessToArtToCoau(Character perFreeAccessToArtToCoau) {
		this.perFreeAccessToArtToCoau = perFreeAccessToArtToCoau;
	}

	@Column(name = "ALLW_COAU_SEE_ART_PRD_STAGES", length = 1)
	public Character getAllwCoauSeeArtPrdStages() {
		return this.allwCoauSeeArtPrdStages;
	}

	public void setAllwCoauSeeArtPrdStages(Character allwCoauSeeArtPrdStages) {
		this.allwCoauSeeArtPrdStages = allwCoauSeeArtPrdStages;
	}

	@Column(name = "PER_COAU_TO_SUBS_REVIEW_PROOFS", length = 1)
	public Character getPerCoauToSubsReviewProofs() {
		return this.perCoauToSubsReviewProofs;
	}

	public void setPerCoauToSubsReviewProofs(Character perCoauToSubsReviewProofs) {
		this.perCoauToSubsReviewProofs = perCoauToSubsReviewProofs;
	}

	@Column(name = "ALLOW_TO_ADD_COLLEAGUES", length = 1)
	public Character getAllowToAddColleagues() {
		return this.allowToAddColleagues;
	}

	public void setAllowToAddColleagues(Character allowToAddColleagues) {
		this.allowToAddColleagues = allowToAddColleagues;
	}

	@Column(name = "ALLOW_ARTICLES_PRD_NONPRD_PATH", length = 1)
	public Character getAllowArticlesPrdNonprdPath() {
		return this.allowArticlesPrdNonprdPath;
	}

	public void setAllowArticlesPrdNonprdPath(
			Character allowArticlesPrdNonprdPath) {
		this.allowArticlesPrdNonprdPath = allowArticlesPrdNonprdPath;
	}

	@Column(name = "COLLEC_A_CONF_OF_INTRST_FORM", length = 1)
	public Character getCollecAConfOfIntrstForm() {
		return this.collecAConfOfIntrstForm;
	}

	public void setCollecAConfOfIntrstForm(Character collecAConfOfIntrstForm) {
		this.collecAConfOfIntrstForm = collecAConfOfIntrstForm;
	}

	@Column(name = "DISP_WRNGS_AUTH_MSNG_LICAGRMNT", length = 1)
	public Character getDispWrngsAuthMsngLicagrmnt() {
		return this.dispWrngsAuthMsngLicagrmnt;
	}

	public void setDispWrngsAuthMsngLicagrmnt(
			Character dispWrngsAuthMsngLicagrmnt) {
		this.dispWrngsAuthMsngLicagrmnt = dispWrngsAuthMsngLicagrmnt;
	}

	@Column(name = "COAUTH_RECEIVE_INVITATION", length = 1)
	public Character getCoauthReceiveInvitation() {
		return this.coauthReceiveInvitation;
	}

	public void setCoauthReceiveInvitation(Character coauthReceiveInvitation) {
		this.coauthReceiveInvitation = coauthReceiveInvitation;
	}

	@Column(name = "JOU_NICKNAME", length = 100)
	public String getJouNickname() {
		return this.jouNickname;
	}

	public void setJouNickname(String jouNickname) {
		this.jouNickname = jouNickname;
	}

	@Column(name = "DISP_OR_EMAIL_MRKTNG_TO_USR", length = 1)
	public Character getDispOrEmailMrktngToUsr() {
		return this.dispOrEmailMrktngToUsr;
	}

	public void setDispOrEmailMrktngToUsr(Character dispOrEmailMrktngToUsr) {
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
	}

	@Column(name = "DISP_OR_EMAIL_SURVEY_TO_USR", length = 1)
	public Character getDispOrEmailSurveyToUsr() {
		return this.dispOrEmailSurveyToUsr;
	}

	public void setDispOrEmailSurveyToUsr(Character dispOrEmailSurveyToUsr) {
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOU_INVITED_IN_AS_START_DT", length = 7)
	public Date getJouInvitedInAsStartDt() {
		return this.jouInvitedInAsStartDt;
	}

	public void setJouInvitedInAsStartDt(Date jouInvitedInAsStartDt) {
		this.jouInvitedInAsStartDt = jouInvitedInAsStartDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOU_INVITED_IN_AS_END_DT", length = 7)
	public Date getJouInvitedInAsEndDt() {
		return this.jouInvitedInAsEndDt;
	}

	public void setJouInvitedInAsEndDt(Date jouInvitedInAsEndDt) {
		this.jouInvitedInAsEndDt = jouInvitedInAsEndDt;
	}

	@Column(name = "CREATED_BY", length = 25)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", length = 25)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journals")
	public Set<UserPreferredJournals> getUserPreferredJournalses() {
		return this.userPreferredJournalses;
	}

	public void setUserPreferredJournalses(
			Set<UserPreferredJournals> userPreferredJournalses) {
		this.userPreferredJournalses = userPreferredJournalses;
	}

}
