package com.wiley.gr.ace.authorservices.persistence.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LookupValues generated by hbm2java
 */
@Entity
@Table(name = "LOOKUP_VALUES")
public class LookupValues implements java.io.Serializable {

	private LookupValuesId id;

	public LookupValues() {
	}

	public LookupValues(LookupValuesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lookupKey", column = @Column(name = "LOOKUP_KEY", length = 50)),
			@AttributeOverride(name = "lookupName", column = @Column(name = "LOOKUP_NAME", length = 250)),
			@AttributeOverride(name = "lookupValue", column = @Column(name = "LOOKUP_VALUE", length = 1000)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", length = 50)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", length = 7)),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UPDATED_BY", length = 50)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UPDATED_DATE", length = 7)) })
	public LookupValuesId getId() {
		return this.id;
	}

	public void setId(LookupValuesId id) {
		this.id = id;
	}

}
