package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LookupValues generated by hbm2java
 */
@Entity
@Table(name = "LOOKUP_VALUES")
public class LookupValues implements java.io.Serializable {

	private Integer lookupId;
	private String lookupKey;
	private String lookupName;
	private String lookupValue;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public LookupValues() {
	}

	public LookupValues(Integer lookupId) {
		this.lookupId = lookupId;
	}

	public LookupValues(Integer lookupId, String lookupKey, String lookupName,
			String lookupValue, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate) {
		this.lookupId = lookupId;
		this.lookupKey = lookupKey;
		this.lookupName = lookupName;
		this.lookupValue = lookupValue;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "LOOKUP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getLookupId() {
		return this.lookupId;
	}

	public void setLookupId(Integer lookupId) {
		this.lookupId = lookupId;
	}

	@Column(name = "LOOKUP_KEY", length = 50)
	public String getLookupKey() {
		return this.lookupKey;
	}

	public void setLookupKey(String lookupKey) {
		this.lookupKey = lookupKey;
	}

	@Column(name = "LOOKUP_NAME", length = 250)
	public String getLookupName() {
		return this.lookupName;
	}

	public void setLookupName(String lookupName) {
		this.lookupName = lookupName;
	}

	@Column(name = "LOOKUP_VALUE", length = 1000)
	public String getLookupValue() {
		return this.lookupValue;
	}

	public void setLookupValue(String lookupValue) {
		this.lookupValue = lookupValue;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
