/*******************************************************************************
 * Copyright (c) 2015 John Wiley & Sons, Inc. All rights reserved.
 *
 * All material contained herein is proprietary to John Wiley & Sons 
 * and its third party suppliers, if any. The methods, techniques and 
 * technical concepts contained herein are considered trade secrets 
 * and confidential and may be protected by intellectual property laws.  
 * Reproduction or distribution of this material, in whole or in part, 
 * is strictly forbidden except by express prior written permission 
 * of John Wiley & Sons.
 *******************************************************************************/
package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LookupValuesId generated by hbm2java
 */
@Embeddable
public class LookupValuesId implements java.io.Serializable {

	private String lookupKey;
	private String lookupName;
	private String lookupValue;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public LookupValuesId() {
	}

	public LookupValuesId(String lookupKey, String lookupName,
			String lookupValue, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate) {
		this.lookupKey = lookupKey;
		this.lookupName = lookupName;
		this.lookupValue = lookupValue;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Column(name = "LOOKUP_KEY", length = 50)
	public String getLookupKey() {
		return this.lookupKey;
	}

	public void setLookupKey(String lookupKey) {
		this.lookupKey = lookupKey;
	}

	@Column(name = "LOOKUP_NAME", length = 250)
	public String getLookupName() {
		return this.lookupName;
	}

	public void setLookupName(String lookupName) {
		this.lookupName = lookupName;
	}

	@Column(name = "LOOKUP_VALUE", length = 1000)
	public String getLookupValue() {
		return this.lookupValue;
	}

	public void setLookupValue(String lookupValue) {
		this.lookupValue = lookupValue;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/*public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LookupValuesId))
			return false;
		LookupValuesId castOther = (LookupValuesId) other;

		return ((this.getLookupKey() == castOther.getLookupKey()) || (this
				.getLookupKey() != null && castOther.getLookupKey() != null && this
				.getLookupKey().equals(castOther.getLookupKey())))
				&& ((this.getLookupName() == castOther.getLookupName()) || (this
						.getLookupName() != null
						&& castOther.getLookupName() != null && this
						.getLookupName().equals(castOther.getLookupName())))
				&& ((this.getLookupValue() == castOther.getLookupValue()) || (this
						.getLookupValue() != null
						&& castOther.getLookupValue() != null && this
						.getLookupValue().equals(castOther.getLookupValue())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate()) || (this
						.getCreatedDate() != null
						&& castOther.getCreatedDate() != null && this
						.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this
						.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this
						.getUpdatedBy().equals(castOther.getUpdatedBy())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate()) || (this
						.getUpdatedDate() != null
						&& castOther.getUpdatedDate() != null && this
						.getUpdatedDate().equals(castOther.getUpdatedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLookupKey() == null ? 0 : this.getLookupKey().hashCode());
		result = 37
				* result
				+ (getLookupName() == null ? 0 : this.getLookupName()
						.hashCode());
		result = 37
				* result
				+ (getLookupValue() == null ? 0 : this.getLookupValue()
						.hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37
				* result
				+ (getCreatedDate() == null ? 0 : this.getCreatedDate()
						.hashCode());
		result = 37 * result
				+ (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37
				* result
				+ (getUpdatedDate() == null ? 0 : this.getUpdatedDate()
						.hashCode());
		return result;
	}*/

}
