package com.wiley.gr.ace.authorservices.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId implements java.io.Serializable {
    
    private Integer userId;
    private int roleId;
    
    public UserRolesId() {
    }
    
    public UserRolesId(Integer userId, int roleId) {
        this.userId = userId;
        this.roleId = roleId;
    }
    
    @Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name = "ROLE_ID", nullable = false, precision = 22, scale = 0)
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }
    
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserRolesId))
            return false;
        UserRolesId castOther = (UserRolesId) other;
        
        return ((this.getUserId() == castOther.getUserId()) || (this
                .getUserId() != null && castOther.getUserId() != null && this
                .getUserId().equals(castOther.getUserId())))
                && (this.getRoleId() == castOther.getRoleId());
    }
    
    public int hashCode() {
        int result = 17;
        
        result = 37 * result
                + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + this.getRoleId();
        return result;
    }
    
}
