package com.wiley.gr.ace.authorservices.persistence.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserSocietyDetails generated by hbm2java
 */
@Entity
@Table(name = "USER_SOCIETY_DETAILS")
public class UserSocietyDetails implements java.io.Serializable {
    
    private Integer societyId;
    private AuthorProfile authorProfile;
    private String societyName;
    private String membershipNo;
    private String promoCode;
    private String discountFlgOoOrOaPricing;
    private Date startDt;
    private Date endDt;
    private Date createdDate;
    private String createdBy;
    private String updatedBy;
    private Date updatedDate;
    
    public UserSocietyDetails() {
    }
    
    public UserSocietyDetails(Integer societyId) {
        this.societyId = societyId;
    }
    
    public UserSocietyDetails(Integer societyId, AuthorProfile authorProfile,
            String societyName, String membershipNo, String promoCode,
            String discountFlgOoOrOaPricing, Date startDt, Date endDt,
            Date createdDate, String createdBy, String updatedBy,
            Date updatedDate) {
        this.societyId = societyId;
        this.authorProfile = authorProfile;
        this.societyName = societyName;
        this.membershipNo = membershipNo;
        this.promoCode = promoCode;
        this.discountFlgOoOrOaPricing = discountFlgOoOrOaPricing;
        this.startDt = startDt;
        this.endDt = endDt;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
    }
    
    @Id
    @Column(name = "SOCIETY_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getSocietyId() {
        return this.societyId;
    }
    
    public void setSocietyId(Integer societyId) {
        this.societyId = societyId;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "USER_ID")
    public AuthorProfile getAuthorProfile() {
        return this.authorProfile;
    }
    
    public void setAuthorProfile(AuthorProfile authorProfile) {
        this.authorProfile = authorProfile;
    }
    
    @Column(name = "SOCIETY_NAME", length = 1000)
    public String getSocietyName() {
        return this.societyName;
    }
    
    public void setSocietyName(String societyName) {
        this.societyName = societyName;
    }
    
    @Column(name = "MEMBERSHIP_NO", length = 50)
    public String getMembershipNo() {
        return this.membershipNo;
    }
    
    public void setMembershipNo(String membershipNo) {
        this.membershipNo = membershipNo;
    }
    
    @Column(name = "PROMO_CODE", length = 50)
    public String getPromoCode() {
        return this.promoCode;
    }
    
    public void setPromoCode(String promoCode) {
        this.promoCode = promoCode;
    }
    
    @Column(name = "DISCOUNT_FLG_OO_OR_OA_PRICING", length = 2)
    public String getDiscountFlgOoOrOaPricing() {
        return this.discountFlgOoOrOaPricing;
    }
    
    public void setDiscountFlgOoOrOaPricing(String discountFlgOoOrOaPricing) {
        this.discountFlgOoOrOaPricing = discountFlgOoOrOaPricing;
    }
    
    @Column(name = "START_DT")
    public Date getStartDt() {
        return this.startDt;
    }
    
    public void setStartDt(Date startDt) {
        this.startDt = startDt;
    }
    
    @Column(name = "END_DT")
    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }
    
    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name = "CREATED_BY", length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    
    @Column(name = "UPDATED_BY", length = 100)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    
}
