package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAffiliations generated by hbm2java
 */
public class UserAffiliations implements java.io.Serializable {

	private Integer affiliationId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private String institutionCd;
	private String institutionName;
	private String departmentCd;
	private String departmentName;
	private String townOrCityName;
	private String stateOrProvinceName;
	private Date startDt;
	private Date endDt;
	private Date cratedDate;
	private Date updatedDate;

	public UserAffiliations() {
	}

	public UserAffiliations(Integer affiliationId) {
		this.affiliationId = affiliationId;
	}

	public UserAffiliations(Integer affiliationId, Users usersByCreatedBy,
			Users usersByUpdatedBy, AuthorProfile authorProfile,
			String institutionCd, String institutionName, String departmentCd,
			String departmentName, String townOrCityName,
			String stateOrProvinceName, Date startDt, Date endDt,
			Date cratedDate, Date updatedDate) {
		this.affiliationId = affiliationId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.institutionCd = institutionCd;
		this.institutionName = institutionName;
		this.departmentCd = departmentCd;
		this.departmentName = departmentName;
		this.townOrCityName = townOrCityName;
		this.stateOrProvinceName = stateOrProvinceName;
		this.startDt = startDt;
		this.endDt = endDt;
		this.cratedDate = cratedDate;
		this.updatedDate = updatedDate;
	}

	public Integer getAffiliationId() {
		return this.affiliationId;
	}

	public void setAffiliationId(Integer affiliationId) {
		this.affiliationId = affiliationId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	public String getInstitutionCd() {
		return this.institutionCd;
	}

	public void setInstitutionCd(String institutionCd) {
		this.institutionCd = institutionCd;
	}

	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	public String getDepartmentCd() {
		return this.departmentCd;
	}

	public void setDepartmentCd(String departmentCd) {
		this.departmentCd = departmentCd;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getTownOrCityName() {
		return this.townOrCityName;
	}

	public void setTownOrCityName(String townOrCityName) {
		this.townOrCityName = townOrCityName;
	}

	public String getStateOrProvinceName() {
		return this.stateOrProvinceName;
	}

	public void setStateOrProvinceName(String stateOrProvinceName) {
		this.stateOrProvinceName = stateOrProvinceName;
	}

	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	public Date getCratedDate() {
		return this.cratedDate;
	}

	public void setCratedDate(Date cratedDate) {
		this.cratedDate = cratedDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
