package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserFunderGrants generated by hbm2java
 */
public class UserFunderGrants implements java.io.Serializable {

	private Integer userFunderGrantId;
	private ResearchFunders researchFunders;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private String grantNum;
	private Date createdDate;
	private Date updatedDate;

	public UserFunderGrants() {
	}

	public UserFunderGrants(Integer userFunderGrantId) {
		this.userFunderGrantId = userFunderGrantId;
	}

	public UserFunderGrants(Integer userFunderGrantId,
			ResearchFunders researchFunders, Users usersByCreatedBy,
			Users usersByUpdatedBy, AuthorProfile authorProfile,
			String grantNum, Date createdDate, Date updatedDate) {
		this.userFunderGrantId = userFunderGrantId;
		this.researchFunders = researchFunders;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.grantNum = grantNum;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Integer getUserFunderGrantId() {
		return this.userFunderGrantId;
	}

	public void setUserFunderGrantId(Integer userFunderGrantId) {
		this.userFunderGrantId = userFunderGrantId;
	}

	public ResearchFunders getResearchFunders() {
		return this.researchFunders;
	}

	public void setResearchFunders(ResearchFunders researchFunders) {
		this.researchFunders = researchFunders;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	public String getGrantNum() {
		return this.grantNum;
	}

	public void setGrantNum(String grantNum) {
		this.grantNum = grantNum;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
