package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserPreferredJournals generated by hbm2java
 */
public class UserPreferredJournals implements java.io.Serializable {

	private UserPreferredJournalsId id;
	private Journals journals;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;

	public UserPreferredJournals() {
	}

	public UserPreferredJournals(UserPreferredJournalsId id) {
		this.id = id;
	}

	public UserPreferredJournals(UserPreferredJournalsId id, Journals journals,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			AuthorProfile authorProfile) {
		this.id = id;
		this.journals = journals;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
	}

	public UserPreferredJournalsId getId() {
		return this.id;
	}

	public void setId(UserPreferredJournalsId id) {
		this.id = id;
	}

	public Journals getJournals() {
		return this.journals;
	}

	public void setJournals(Journals journals) {
		this.journals = journals;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

}
