/*******************************************************************************
 * Copyright (c) 2015 John Wiley & Sons, Inc. All rights reserved.
 *
 * All material contained herein is proprietary to John Wiley & Sons 
 * and its third party suppliers, if any. The methods, techniques and 
 * technical concepts contained herein are considered trade secrets 
 * and confidential and may be protected by intellectual property laws.  
 * Reproduction or distribution of this material, in whole or in part, 
 * is strictly forbidden except by express prior written permission 
 * of John Wiley & Sons.
 *******************************************************************************/
package com.wiley.gr.ace.authorservices.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserReferenceDataId generated by hbm2java
 */
@Embeddable
public class UserReferenceDataId implements java.io.Serializable {

	private int userId;
	private String ecid;

	public UserReferenceDataId() {
	}

	public UserReferenceDataId(int userId, String ecid) {
		this.userId = userId;
		this.ecid = ecid;
	}

	@Column(name = "USER_ID", nullable = false, precision = 22, scale = 0)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "ECID", nullable = false, length = 15)
	public String getEcid() {
		return this.ecid;
	}

	public void setEcid(String ecid) {
		this.ecid = ecid;
	}

	/*public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserReferenceDataId))
			return false;
		UserReferenceDataId castOther = (UserReferenceDataId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getEcid() == castOther.getEcid()) || (this.getEcid() != null
						&& castOther.getEcid() != null && this.getEcid()
						.equals(castOther.getEcid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getEcid() == null ? 0 : this.getEcid().hashCode());
		return result;
	}*/

}
