package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 4:56:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserSocietyDetails generated by hbm2java
 */
public class UserSocietyDetails implements java.io.Serializable {

	private Integer societyId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AuthorProfile authorProfile;
	private String societyCd;
	private String societyName;
	private String membershipNo;
	private String promoCode;
	private String discountFlgOoOrOaPricing;
	private Date startDt;
	private Date endDt;
	private Date createdDate;
	private Date updatedDate;

	public UserSocietyDetails() {
	}

	public UserSocietyDetails(Integer societyId) {
		this.societyId = societyId;
	}

	public UserSocietyDetails(Integer societyId, Users usersByCreatedBy,
			Users usersByUpdatedBy, AuthorProfile authorProfile,
			String societyCd, String societyName, String membershipNo,
			String promoCode, String discountFlgOoOrOaPricing, Date startDt,
			Date endDt, Date createdDate, Date updatedDate) {
		this.societyId = societyId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.authorProfile = authorProfile;
		this.societyCd = societyCd;
		this.societyName = societyName;
		this.membershipNo = membershipNo;
		this.promoCode = promoCode;
		this.discountFlgOoOrOaPricing = discountFlgOoOrOaPricing;
		this.startDt = startDt;
		this.endDt = endDt;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Integer getSocietyId() {
		return this.societyId;
	}

	public void setSocietyId(Integer societyId) {
		this.societyId = societyId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public AuthorProfile getAuthorProfile() {
		return this.authorProfile;
	}

	public void setAuthorProfile(AuthorProfile authorProfile) {
		this.authorProfile = authorProfile;
	}

	public String getSocietyCd() {
		return this.societyCd;
	}

	public void setSocietyCd(String societyCd) {
		this.societyCd = societyCd;
	}

	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	public String getMembershipNo() {
		return this.membershipNo;
	}

	public void setMembershipNo(String membershipNo) {
		this.membershipNo = membershipNo;
	}

	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

	public String getDiscountFlgOoOrOaPricing() {
		return this.discountFlgOoOrOaPricing;
	}

	public void setDiscountFlgOoOrOaPricing(String discountFlgOoOrOaPricing) {
		this.discountFlgOoOrOaPricing = discountFlgOoOrOaPricing;
	}

	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
