package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdditionalPermissions generated by hbm2java
 */
@Entity
@Table(name = "additional_permissions", catalog = "as2_app_db")
public class AdditionalPermissions implements java.io.Serializable {

	private Long additionalPermissionsId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByUserId;
	private ObjectTypes objectTypes;
	private Permissions permissions;
	private Date permEndDt;
	private Long objectId;
	private Date createdDate;
	private Date updatedDate;

	public AdditionalPermissions() {
	}

	public AdditionalPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public AdditionalPermissions(Users usersByCreatedBy,
			Users usersByUpdatedBy, Users usersByUserId,
			ObjectTypes objectTypes, Permissions permissions, Date permEndDt,
			Long objectId, Date createdDate, Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByUserId = usersByUserId;
		this.objectTypes = objectTypes;
		this.permissions = permissions;
		this.permEndDt = permEndDt;
		this.objectId = objectId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADDITIONAL_PERMISSIONS_ID", unique = true, nullable = false)
	public Long getAdditionalPermissionsId() {
		return this.additionalPermissionsId;
	}

	public void setAdditionalPermissionsId(Long additionalPermissionsId) {
		this.additionalPermissionsId = additionalPermissionsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBJECT_TYPE_CD")
	public ObjectTypes getObjectTypes() {
		return this.objectTypes;
	}

	public void setObjectTypes(ObjectTypes objectTypes) {
		this.objectTypes = objectTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_CD", nullable = false)
	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PERM_END_DT", length = 19)
	public Date getPermEndDt() {
		return this.permEndDt;
	}

	public void setPermEndDt(Date permEndDt) {
		this.permEndDt = permEndDt;
	}

	@Column(name = "OBJECT_ID")
	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
