package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AdditionalPermissions generated by hbm2java
 */
public class AdditionalPermissions implements java.io.Serializable {

	private Long additionalPermissionsId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByUserId;
	private ObjectTypes objectTypes;
	private Permissions permissions;
	private Date permEndDt;
	private Long objectId;
	private Date createdDate;
	private Date updatedDate;

	public AdditionalPermissions() {
	}

	public AdditionalPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public AdditionalPermissions(Users usersByCreatedBy,
			Users usersByUpdatedBy, Users usersByUserId,
			ObjectTypes objectTypes, Permissions permissions, Date permEndDt,
			Long objectId, Date createdDate, Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByUserId = usersByUserId;
		this.objectTypes = objectTypes;
		this.permissions = permissions;
		this.permEndDt = permEndDt;
		this.objectId = objectId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Long getAdditionalPermissionsId() {
		return this.additionalPermissionsId;
	}

	public void setAdditionalPermissionsId(Long additionalPermissionsId) {
		this.additionalPermissionsId = additionalPermissionsId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	public ObjectTypes getObjectTypes() {
		return this.objectTypes;
	}

	public void setObjectTypes(ObjectTypes objectTypes) {
		this.objectTypes = objectTypes;
	}

	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public Date getPermEndDt() {
		return this.permEndDt;
	}

	public void setPermEndDt(Date permEndDt) {
		this.permEndDt = permEndDt;
	}

	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
