package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerts generated by hbm2java
 */
@Entity
@Table(name = "alerts", catalog = "as2_app_db")
public class Alerts implements java.io.Serializable {

	private String alertCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private AlertTypes alertTypes;
	private String alertName;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private Set<JournalAlertsConfiguration> journalAlertsConfigurations = new HashSet<JournalAlertsConfiguration>(
			0);
	private Set<UserAlerts> userAlertses = new HashSet<UserAlerts>(0);

	public Alerts() {
	}

	public Alerts(String alertCd) {
		this.alertCd = alertCd;
	}

	public Alerts(String alertCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, AlertTypes alertTypes, String alertName,
			String description, Date createdDate, Date updatedDate,
			Set<JournalAlertsConfiguration> journalAlertsConfigurations,
			Set<UserAlerts> userAlertses) {
		this.alertCd = alertCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.alertTypes = alertTypes;
		this.alertName = alertName;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.journalAlertsConfigurations = journalAlertsConfigurations;
		this.userAlertses = userAlertses;
	}

	@Id
	@Column(name = "ALERT_CD", unique = true, nullable = false, length = 15)
	public String getAlertCd() {
		return this.alertCd;
	}

	public void setAlertCd(String alertCd) {
		this.alertCd = alertCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALERT_TYPE_CD")
	public AlertTypes getAlertTypes() {
		return this.alertTypes;
	}

	public void setAlertTypes(AlertTypes alertTypes) {
		this.alertTypes = alertTypes;
	}

	@Column(name = "ALERT_NAME", length = 250)
	public String getAlertName() {
		return this.alertName;
	}

	public void setAlertName(String alertName) {
		this.alertName = alertName;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerts")
	public Set<JournalAlertsConfiguration> getJournalAlertsConfigurations() {
		return this.journalAlertsConfigurations;
	}

	public void setJournalAlertsConfigurations(
			Set<JournalAlertsConfiguration> journalAlertsConfigurations) {
		this.journalAlertsConfigurations = journalAlertsConfigurations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alerts")
	public Set<UserAlerts> getUserAlertses() {
		return this.userAlertses;
	}

	public void setUserAlertses(Set<UserAlerts> userAlertses) {
		this.userAlertses = userAlertses;
	}

}
