package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AreaOfInterest generated by hbm2java
 */
@Entity
@Table(name = "area_of_interest", catalog = "as2_app_db")
public class AreaOfInterest implements java.io.Serializable {

	private String areaOfInterestCd;
	private String interestName;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;

	public AreaOfInterest() {
	}

	public AreaOfInterest(String areaOfInterestCd) {
		this.areaOfInterestCd = areaOfInterestCd;
	}

	public AreaOfInterest(String areaOfInterestCd, String interestName,
			Date createdDate, UUID createdBy, Date updatedDate, UUID updatedBy) {
		this.areaOfInterestCd = areaOfInterestCd;
		this.interestName = interestName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "AREA_OF_INTEREST_CD", unique = true, nullable = false, length = 15)
	public String getAreaOfInterestCd() {
		return this.areaOfInterestCd;
	}

	public void setAreaOfInterestCd(String areaOfInterestCd) {
		this.areaOfInterestCd = areaOfInterestCd;
	}

	@Column(name = "INTEREST_NAME", length = 250)
	public String getInterestName() {
		return this.interestName;
	}

	public void setInterestName(String interestName) {
		this.interestName = interestName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

}
