package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 18, 2015 11:29:00 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArticleRoles generated by hbm2java
 */
@Entity
@Table(name = "ARTICLE_ROLES")
public class ArticleRoles implements java.io.Serializable {

	private String articleRoleCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String articleRoleName;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private Set<ArticleAuthorAssignment> articleAuthorAssignments = new HashSet<ArticleAuthorAssignment>(
			0);

	public ArticleRoles() {
	}

	public ArticleRoles(String articleRoleCd) {
		this.articleRoleCd = articleRoleCd;
	}

	public ArticleRoles(String articleRoleCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String articleRoleName, String description,
			Date createdDate, Date updatedDate,
			Set<ArticleAuthorAssignment> articleAuthorAssignments) {
		this.articleRoleCd = articleRoleCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.articleRoleName = articleRoleName;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.articleAuthorAssignments = articleAuthorAssignments;
	}

	@Id
	@Column(name = "ARTICLE_ROLE_CD", unique = true, nullable = false, length = 15)
	public String getArticleRoleCd() {
		return this.articleRoleCd;
	}

	public void setArticleRoleCd(String articleRoleCd) {
		this.articleRoleCd = articleRoleCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "ARTICLE_ROLE_NAME", length = 100)
	public String getArticleRoleName() {
		return this.articleRoleName;
	}

	public void setArticleRoleName(String articleRoleName) {
		this.articleRoleName = articleRoleName;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articleRoles")
	public Set<ArticleAuthorAssignment> getArticleAuthorAssignments() {
		return this.articleAuthorAssignments;
	}

	public void setArticleAuthorAssignments(
			Set<ArticleAuthorAssignment> articleAuthorAssignments) {
		this.articleAuthorAssignments = articleAuthorAssignments;
	}

}
