package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 22, 2015 4:46:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArticleConfiguration generated by hbm2java
 */
@Entity
@Table(name = "article_configuration", catalog = "as2_app_db")
public class ArticleConfiguration implements java.io.Serializable {

	private long dhId;
	private Boolean prodTrkPathArticle;
	private byte[] notes;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public ArticleConfiguration() {
	}

	public ArticleConfiguration(long dhId) {
		this.dhId = dhId;
	}

	public ArticleConfiguration(long dhId, Boolean prodTrkPathArticle,
			byte[] notes, Date createdDate, Long createdBy, Date updatedDate,
			Long updatedBy) {
		this.dhId = dhId;
		this.prodTrkPathArticle = prodTrkPathArticle;
		this.notes = notes;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "DH_ID", unique = true, nullable = false)
	public long getDhId() {
		return this.dhId;
	}

	public void setDhId(long dhId) {
		this.dhId = dhId;
	}

	@Column(name = "PROD_TRK_PATH_ARTICLE", length = 1)
	public Boolean getProdTrkPathArticle() {
		return this.prodTrkPathArticle;
	}

	public void setProdTrkPathArticle(Boolean prodTrkPathArticle) {
		this.prodTrkPathArticle = prodTrkPathArticle;
	}

	@Column(name = "NOTES")
	public byte[] getNotes() {
		return this.notes;
	}

	public void setNotes(byte[] notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
