package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 16, 2015 3:47:59 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditDetails generated by hbm2java
 */
@Entity
@Table(name = "audit_details", catalog = "as2_app_db")
public class AuditDetails implements java.io.Serializable {

	private Integer auditId;
	private Actions actions;
	private ObjectTypes objectTypes;
	private String objName;
	private String objAttribute;
	private byte[] participantId;
	private Integer objId;
	private String oldVal;
	private String newVal;
	private Date createdDate;
	private byte[] createdBy;
	private Date updatedDate;
	private byte[] updatedBy;

	public AuditDetails() {
	}

	public AuditDetails(byte[] createdBy, byte[] updatedBy) {
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	public AuditDetails(Actions actions, ObjectTypes objectTypes,
			String objName, String objAttribute, byte[] participantId,
			Integer objId, String oldVal, String newVal, Date createdDate,
			byte[] createdBy, Date updatedDate, byte[] updatedBy) {
		this.actions = actions;
		this.objectTypes = objectTypes;
		this.objName = objName;
		this.objAttribute = objAttribute;
		this.participantId = participantId;
		this.objId = objId;
		this.oldVal = oldVal;
		this.newVal = newVal;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUDIT_ID", unique = true, nullable = false)
	public Integer getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Integer auditId) {
		this.auditId = auditId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTION_CD")
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBJ_TYPE_CD")
	public ObjectTypes getObjectTypes() {
		return this.objectTypes;
	}

	public void setObjectTypes(ObjectTypes objectTypes) {
		this.objectTypes = objectTypes;
	}

	@Column(name = "OBJ_NAME", length = 50)
	public String getObjName() {
		return this.objName;
	}

	public void setObjName(String objName) {
		this.objName = objName;
	}

	@Column(name = "OBJ_ATTRIBUTE", length = 50)
	public String getObjAttribute() {
		return this.objAttribute;
	}

	public void setObjAttribute(String objAttribute) {
		this.objAttribute = objAttribute;
	}

	@Column(name = "PARTICIPANT_ID")
	public byte[] getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(byte[] participantId) {
		this.participantId = participantId;
	}

	@Column(name = "OBJ_ID")
	public Integer getObjId() {
		return this.objId;
	}

	public void setObjId(Integer objId) {
		this.objId = objId;
	}

	@Column(name = "OLD_VAL", length = 250)
	public String getOldVal() {
		return this.oldVal;
	}

	public void setOldVal(String oldVal) {
		this.oldVal = oldVal;
	}

	@Column(name = "NEW_VAL", length = 250)
	public String getNewVal() {
		return this.newVal;
	}

	public void setNewVal(String newVal) {
		this.newVal = newVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY", nullable = false)
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

}
