package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditDetails generated by hbm2java
 */
@Entity
@Table(name = "audit_details", catalog = "as2_app_db")
public class AuditDetails implements java.io.Serializable {

	private Long auditId;
	private Actions actions;
	private Users users;
	private ObjectTypes objectTypes;
	private String objName;
	private String objAttribute;
	private Long objectId;
	private Long primarykeycolumn1;
	private Long primarykeycolumn2;
	private String oldVal;
	private String newVal;
	private Date createdDate;

	public AuditDetails() {
	}

	public AuditDetails(Actions actions, Users users, ObjectTypes objectTypes,
			String objName, String objAttribute, Long objectId,
			Long primarykeycolumn1, Long primarykeycolumn2, String oldVal,
			String newVal, Date createdDate) {
		this.actions = actions;
		this.users = users;
		this.objectTypes = objectTypes;
		this.objName = objName;
		this.objAttribute = objAttribute;
		this.objectId = objectId;
		this.primarykeycolumn1 = primarykeycolumn1;
		this.primarykeycolumn2 = primarykeycolumn2;
		this.oldVal = oldVal;
		this.newVal = newVal;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUDIT_ID", unique = true, nullable = false)
	public Long getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Long auditId) {
		this.auditId = auditId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTION_CD")
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OBJECT_TYPE_CD")
	public ObjectTypes getObjectTypes() {
		return this.objectTypes;
	}

	public void setObjectTypes(ObjectTypes objectTypes) {
		this.objectTypes = objectTypes;
	}

	@Column(name = "OBJ_NAME", length = 50)
	public String getObjName() {
		return this.objName;
	}

	public void setObjName(String objName) {
		this.objName = objName;
	}

	@Column(name = "OBJ_ATTRIBUTE", length = 50)
	public String getObjAttribute() {
		return this.objAttribute;
	}

	public void setObjAttribute(String objAttribute) {
		this.objAttribute = objAttribute;
	}

	@Column(name = "OBJECT_ID")
	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	@Column(name = "PRIMARYKEYCOLUMN1")
	public Long getPrimarykeycolumn1() {
		return this.primarykeycolumn1;
	}

	public void setPrimarykeycolumn1(Long primarykeycolumn1) {
		this.primarykeycolumn1 = primarykeycolumn1;
	}

	@Column(name = "PRIMARYKEYCOLUMN2")
	public Long getPrimarykeycolumn2() {
		return this.primarykeycolumn2;
	}

	public void setPrimarykeycolumn2(Long primarykeycolumn2) {
		this.primarykeycolumn2 = primarykeycolumn2;
	}

	@Column(name = "OLD_VAL", length = 250)
	public String getOldVal() {
		return this.oldVal;
	}

	public void setOldVal(String oldVal) {
		this.oldVal = oldVal;
	}

	@Column(name = "NEW_VAL", length = 250)
	public String getNewVal() {
		return this.newVal;
	}

	public void setNewVal(String newVal) {
		this.newVal = newVal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
