package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthCoauthDetails generated by hbm2java
 */
@Entity
@Table(name = "auth_coauth_details", catalog = "as2_app_db")
public class AuthCoauthDetails implements java.io.Serializable {

	private Long authCoauthId;
	private UserProfile userProfileByAuthorUserId;
	private UserProfile userProfileByCoauthUserId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String coauthTitle;
	private String coauthFirstName;
	private String coauthLastName;
	private String coauthEmailAddr;
	private String coauthPhone;
	private String coauthInstitutionCd;
	private String coauthInstitutionName;
	private String coauthDepartmentCd;
	private String coauthDeptName;
	private Date createdDate;
	private Date updatedDate;

	public AuthCoauthDetails() {
	}

	public AuthCoauthDetails(UserProfile userProfileByAuthorUserId,
			UserProfile userProfileByCoauthUserId, Users usersByCreatedBy,
			Users usersByUpdatedBy, String coauthTitle, String coauthFirstName,
			String coauthLastName, String coauthEmailAddr, String coauthPhone,
			String coauthInstitutionCd, String coauthInstitutionName,
			String coauthDepartmentCd, String coauthDeptName, Date createdDate,
			Date updatedDate) {
		this.userProfileByAuthorUserId = userProfileByAuthorUserId;
		this.userProfileByCoauthUserId = userProfileByCoauthUserId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.coauthTitle = coauthTitle;
		this.coauthFirstName = coauthFirstName;
		this.coauthLastName = coauthLastName;
		this.coauthEmailAddr = coauthEmailAddr;
		this.coauthPhone = coauthPhone;
		this.coauthInstitutionCd = coauthInstitutionCd;
		this.coauthInstitutionName = coauthInstitutionName;
		this.coauthDepartmentCd = coauthDepartmentCd;
		this.coauthDeptName = coauthDeptName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUTH_COAUTH_ID", unique = true, nullable = false)
	public Long getAuthCoauthId() {
		return this.authCoauthId;
	}

	public void setAuthCoauthId(Long authCoauthId) {
		this.authCoauthId = authCoauthId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTHOR_USER_ID")
	public UserProfile getUserProfileByAuthorUserId() {
		return this.userProfileByAuthorUserId;
	}

	public void setUserProfileByAuthorUserId(
			UserProfile userProfileByAuthorUserId) {
		this.userProfileByAuthorUserId = userProfileByAuthorUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COAUTH_USER_ID")
	public UserProfile getUserProfileByCoauthUserId() {
		return this.userProfileByCoauthUserId;
	}

	public void setUserProfileByCoauthUserId(
			UserProfile userProfileByCoauthUserId) {
		this.userProfileByCoauthUserId = userProfileByCoauthUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "COAUTH_TITLE", length = 50)
	public String getCoauthTitle() {
		return this.coauthTitle;
	}

	public void setCoauthTitle(String coauthTitle) {
		this.coauthTitle = coauthTitle;
	}

	@Column(name = "COAUTH_FIRST_NAME", length = 100)
	public String getCoauthFirstName() {
		return this.coauthFirstName;
	}

	public void setCoauthFirstName(String coauthFirstName) {
		this.coauthFirstName = coauthFirstName;
	}

	@Column(name = "COAUTH_LAST_NAME", length = 100)
	public String getCoauthLastName() {
		return this.coauthLastName;
	}

	public void setCoauthLastName(String coauthLastName) {
		this.coauthLastName = coauthLastName;
	}

	@Column(name = "COAUTH_EMAIL_ADDR", length = 100)
	public String getCoauthEmailAddr() {
		return this.coauthEmailAddr;
	}

	public void setCoauthEmailAddr(String coauthEmailAddr) {
		this.coauthEmailAddr = coauthEmailAddr;
	}

	@Column(name = "COAUTH_PHONE", length = 15)
	public String getCoauthPhone() {
		return this.coauthPhone;
	}

	public void setCoauthPhone(String coauthPhone) {
		this.coauthPhone = coauthPhone;
	}

	@Column(name = "COAUTH_INSTITUTION_CD", length = 10)
	public String getCoauthInstitutionCd() {
		return this.coauthInstitutionCd;
	}

	public void setCoauthInstitutionCd(String coauthInstitutionCd) {
		this.coauthInstitutionCd = coauthInstitutionCd;
	}

	@Column(name = "COAUTH_INSTITUTION_NAME", length = 100)
	public String getCoauthInstitutionName() {
		return this.coauthInstitutionName;
	}

	public void setCoauthInstitutionName(String coauthInstitutionName) {
		this.coauthInstitutionName = coauthInstitutionName;
	}

	@Column(name = "COAUTH_DEPARTMENT_CD", length = 10)
	public String getCoauthDepartmentCd() {
		return this.coauthDepartmentCd;
	}

	public void setCoauthDepartmentCd(String coauthDepartmentCd) {
		this.coauthDepartmentCd = coauthDepartmentCd;
	}

	@Column(name = "COAUTH_DEPT_NAME", length = 100)
	public String getCoauthDeptName() {
		return this.coauthDeptName;
	}

	public void setCoauthDeptName(String coauthDeptName) {
		this.coauthDeptName = coauthDeptName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
