package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuthColleagueDetails generated by hbm2java
 */
@Entity
@Table(name = "auth_colleague_details", catalog = "as2_app_db")
public class AuthColleagueDetails implements java.io.Serializable {

	private Long authColleagueId;
	private UserProfile userProfileByColleagueUserId;
	private Users usersByCreatedBy;
	private UserProfile userProfileByInvitedAuthorId;
	private Users usersByUpdatedBy;
	private String firstName;
	private String lastName;
	private String emailAddr;
	private Long assignedArticleId;
	private Date createdDate;
	private Date updatedDate;

	public AuthColleagueDetails() {
	}

	public AuthColleagueDetails(UserProfile userProfileByColleagueUserId,
			Users usersByCreatedBy, UserProfile userProfileByInvitedAuthorId,
			Users usersByUpdatedBy, String firstName, String lastName,
			String emailAddr, Long assignedArticleId, Date createdDate,
			Date updatedDate) {
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddr = emailAddr;
		this.assignedArticleId = assignedArticleId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUTH_COLLEAGUE_ID", unique = true, nullable = false)
	public Long getAuthColleagueId() {
		return this.authColleagueId;
	}

	public void setAuthColleagueId(Long authColleagueId) {
		this.authColleagueId = authColleagueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLLEAGUE_USER_ID")
	public UserProfile getUserProfileByColleagueUserId() {
		return this.userProfileByColleagueUserId;
	}

	public void setUserProfileByColleagueUserId(
			UserProfile userProfileByColleagueUserId) {
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INVITED_AUTHOR_ID")
	public UserProfile getUserProfileByInvitedAuthorId() {
		return this.userProfileByInvitedAuthorId;
	}

	public void setUserProfileByInvitedAuthorId(
			UserProfile userProfileByInvitedAuthorId) {
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ADDR", length = 100)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "ASSIGNED_ARTICLE_ID")
	public Long getAssignedArticleId() {
		return this.assignedArticleId;
	}

	public void setAssignedArticleId(Long assignedArticleId) {
		this.assignedArticleId = assignedArticleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
