package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * AuthColleagueDetails generated by hbm2java
 */
public class AuthColleagueDetails implements java.io.Serializable {

	private Long authColleagueId;
	private UserProfile userProfileByColleagueUserId;
	private Users usersByCreatedBy;
	private UserProfile userProfileByInvitedAuthorId;
	private Users usersByUpdatedBy;
	private String firstName;
	private String lastName;
	private String emailAddr;
	private Long assignedArticleId;
	private Date createdDate;
	private Date updatedDate;

	public AuthColleagueDetails() {
	}

	public AuthColleagueDetails(UserProfile userProfileByColleagueUserId,
			Users usersByCreatedBy, UserProfile userProfileByInvitedAuthorId,
			Users usersByUpdatedBy, String firstName, String lastName,
			String emailAddr, Long assignedArticleId, Date createdDate,
			Date updatedDate) {
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddr = emailAddr;
		this.assignedArticleId = assignedArticleId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Long getAuthColleagueId() {
		return this.authColleagueId;
	}

	public void setAuthColleagueId(Long authColleagueId) {
		this.authColleagueId = authColleagueId;
	}

	public UserProfile getUserProfileByColleagueUserId() {
		return this.userProfileByColleagueUserId;
	}

	public void setUserProfileByColleagueUserId(
			UserProfile userProfileByColleagueUserId) {
		this.userProfileByColleagueUserId = userProfileByColleagueUserId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public UserProfile getUserProfileByInvitedAuthorId() {
		return this.userProfileByInvitedAuthorId;
	}

	public void setUserProfileByInvitedAuthorId(
			UserProfile userProfileByInvitedAuthorId) {
		this.userProfileByInvitedAuthorId = userProfileByInvitedAuthorId;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	public Long getAssignedArticleId() {
		return this.assignedArticleId;
	}

	public void setAssignedArticleId(Long assignedArticleId) {
		this.assignedArticleId = assignedArticleId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
