package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CoauthorRequestsOoorders generated by hbm2java
 */
public class CoauthorRequestsOoorders implements java.io.Serializable {

	private Long requestId;
	private Users usersByCreatedBy;
	private Users usersByCoauthUserId;
	private Users usersByUpdatedBy;
	private Products products;
	private String messageFromCoauth;
	private Date createdDate;
	private Date updatedDate;

	public CoauthorRequestsOoorders() {
	}

	public CoauthorRequestsOoorders(Users usersByCreatedBy,
			Users usersByCoauthUserId, Users usersByUpdatedBy,
			Products products, String messageFromCoauth, Date createdDate,
			Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByCoauthUserId = usersByCoauthUserId;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.messageFromCoauth = messageFromCoauth;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByCoauthUserId() {
		return this.usersByCoauthUserId;
	}

	public void setUsersByCoauthUserId(Users usersByCoauthUserId) {
		this.usersByCoauthUserId = usersByCoauthUserId;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public String getMessageFromCoauth() {
		return this.messageFromCoauth;
	}

	public void setMessageFromCoauth(String messageFromCoauth) {
		this.messageFromCoauth = messageFromCoauth;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
