package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CoauthorRequestsOoorders generated by hbm2java
 */
@Entity
@Table(name = "coauthor_requests_ooorders", catalog = "as2_app_db", uniqueConstraints = @UniqueConstraint(columnNames = "DH_ID"))
public class CoauthorRequestsOoorders implements java.io.Serializable {

	private Long requestId;
	private UUID coauthParticipantId;
	private Long dhId;
	private String messageFromCoauth;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;

	public CoauthorRequestsOoorders() {
	}

	public CoauthorRequestsOoorders(UUID coauthParticipantId, Long dhId,
			String messageFromCoauth, Date createdDate, UUID createdBy,
			Date updatedDate, UUID updatedBy) {
		this.coauthParticipantId = coauthParticipantId;
		this.dhId = dhId;
		this.messageFromCoauth = messageFromCoauth;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REQUEST_ID", unique = true, nullable = false)
	public Long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Long requestId) {
		this.requestId = requestId;
	}

	@Column(name = "COAUTH_PARTICIPANT_ID")
	public UUID getCoauthParticipantId() {
		return this.coauthParticipantId;
	}

	public void setCoauthParticipantId(UUID coauthParticipantId) {
		this.coauthParticipantId = coauthParticipantId;
	}

	@Column(name = "DH_ID", unique = true)
	public Long getDhId() {
		return this.dhId;
	}

	public void setDhId(Long dhId) {
		this.dhId = dhId;
	}

	@Column(name = "MESSAGE_FROM_COAUTH", length = 1000)
	public String getMessageFromCoauth() {
		return this.messageFromCoauth;
	}

	public void setMessageFromCoauth(String messageFromCoauth) {
		this.messageFromCoauth = messageFromCoauth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

}
