package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DiscountDetails generated by hbm2java
 */
public class DiscountDetails implements java.io.Serializable {

	private Long discountId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String promoCode;
	private String discountTypeCode;
	private Character discountValueType;
	private String discountType;
	private Long discountValue;
	private Date startDate;
	private Date endDate;
	private Date articlePublishedDate;
	private String countryCd;
	private String societyCd;
	private String journalAcronym;
	private String journalType;
	private String institutionCode;
	private String institutionName;
	private Date createdDate;
	private Date updatedDate;

	public DiscountDetails() {
	}

	public DiscountDetails(Users usersByCreatedBy, Users usersByUpdatedBy,
			String promoCode, String discountTypeCode,
			Character discountValueType, String discountType,
			Long discountValue, Date startDate, Date endDate,
			Date articlePublishedDate, String countryCd, String societyCd,
			String journalAcronym, String journalType, String institutionCode,
			String institutionName, Date createdDate, Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.promoCode = promoCode;
		this.discountTypeCode = discountTypeCode;
		this.discountValueType = discountValueType;
		this.discountType = discountType;
		this.discountValue = discountValue;
		this.startDate = startDate;
		this.endDate = endDate;
		this.articlePublishedDate = articlePublishedDate;
		this.countryCd = countryCd;
		this.societyCd = societyCd;
		this.journalAcronym = journalAcronym;
		this.journalType = journalType;
		this.institutionCode = institutionCode;
		this.institutionName = institutionName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Long getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(Long discountId) {
		this.discountId = discountId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

	public String getDiscountTypeCode() {
		return this.discountTypeCode;
	}

	public void setDiscountTypeCode(String discountTypeCode) {
		this.discountTypeCode = discountTypeCode;
	}

	public Character getDiscountValueType() {
		return this.discountValueType;
	}

	public void setDiscountValueType(Character discountValueType) {
		this.discountValueType = discountValueType;
	}

	public String getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(String discountType) {
		this.discountType = discountType;
	}

	public Long getDiscountValue() {
		return this.discountValue;
	}

	public void setDiscountValue(Long discountValue) {
		this.discountValue = discountValue;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getArticlePublishedDate() {
		return this.articlePublishedDate;
	}

	public void setArticlePublishedDate(Date articlePublishedDate) {
		this.articlePublishedDate = articlePublishedDate;
	}

	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	public String getSocietyCd() {
		return this.societyCd;
	}

	public void setSocietyCd(String societyCd) {
		this.societyCd = societyCd;
	}

	public String getJournalAcronym() {
		return this.journalAcronym;
	}

	public void setJournalAcronym(String journalAcronym) {
		this.journalAcronym = journalAcronym;
	}

	public String getJournalType() {
		return this.journalType;
	}

	public void setJournalType(String journalType) {
		this.journalType = journalType;
	}

	public String getInstitutionCode() {
		return this.institutionCode;
	}

	public void setInstitutionCode(String institutionCode) {
		this.institutionCode = institutionCode;
	}

	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
