package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jul 8, 2015 3:59:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvitationLog generated by hbm2java
 */
@Entity
@Table(name = "INVITATION_LOG")
public class InvitationLog implements java.io.Serializable {

	private Integer invitationId;
	private Products products;
	private UserProfile userProfile;
	private Users users;
	private Integer notificationId;
	private String emailAddr;
	private Date sentDate;

	public InvitationLog() {
	}

	public InvitationLog(Integer invitationId) {
		this.invitationId = invitationId;
	}

	public InvitationLog(Integer invitationId, Products products,
			UserProfile userProfile, Users users, Integer notificationId,
			String emailAddr, Date sentDate) {
		this.invitationId = invitationId;
		this.products = products;
		this.userProfile = userProfile;
		this.users = users;
		this.notificationId = notificationId;
		this.emailAddr = emailAddr;
		this.sentDate = sentDate;
	}

	@Id
	@Column(name = "INVITATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getInvitationId() {
		return this.invitationId;
	}

	public void setInvitationId(Integer invitationId) {
		this.invitationId = invitationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SENT_BY")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "NOTIFICATION_ID", precision = 22, scale = 0)
	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	@Column(name = "EMAIL_ADDR", length = 250)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "SENT_DATE")
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

}
