package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 18, 2015 11:29:00 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Journals generated by hbm2java
 */
@Entity
@Table(name = "JOURNALS")
public class Journals implements java.io.Serializable {

	private Integer journalId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Integer dhId;
	private String setupStateInAs;
	private String nickname;
	private String titleDispOoo;
	private Character discontinued;
	private Character invitedInAs;
	private Date invitedInAsStartDate;
	private Date invitedInAsEndDate;
	private Character dispForOoOrdering;
	private Character prodTrkPath;
	private Character perFreeAccessToArtToCoau;
	private Character allwCoauSeeArtPrdStages;
	private Character perCoauToSubsReviewProofs;
	private Character allowToAddColleagues;
	private Character allowArticlesPrdNonprdPath;
	private Character collecAConfliOfIntrstForm;
	private Character coauthReceiveInvitation;
	private Character dispOrEmailMrktngToUsr;
	private Character dispOrEmailSurveyToUsr;
	private Character perFreeAccessArtToCorau;
	private Date createdDate;
	private Date updatedDate;
	private Set<Articles> articleses = new HashSet<Articles>(0);
	private Set<UserPreferredJournals> userPreferredJournalses = new HashSet<UserPreferredJournals>(
			0);
	private Set<JournalAlerts> journalAlertses = new HashSet<JournalAlerts>(0);

	public Journals() {
	}

	public Journals(Integer journalId) {
		this.journalId = journalId;
	}

	public Journals(Integer journalId, Users usersByCreatedBy,
			Users usersByUpdatedBy, Integer dhId, String setupStateInAs,
			String nickname, String titleDispOoo, Character discontinued,
			Character invitedInAs, Date invitedInAsStartDate,
			Date invitedInAsEndDate, Character dispForOoOrdering,
			Character prodTrkPath, Character perFreeAccessToArtToCoau,
			Character allwCoauSeeArtPrdStages,
			Character perCoauToSubsReviewProofs,
			Character allowToAddColleagues,
			Character allowArticlesPrdNonprdPath,
			Character collecAConfliOfIntrstForm,
			Character coauthReceiveInvitation,
			Character dispOrEmailMrktngToUsr, Character dispOrEmailSurveyToUsr,
			Character perFreeAccessArtToCorau, Date createdDate,
			Date updatedDate, Set<Articles> articleses,
			Set<UserPreferredJournals> userPreferredJournalses,
			Set<JournalAlerts> journalAlertses) {
		this.journalId = journalId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.dhId = dhId;
		this.setupStateInAs = setupStateInAs;
		this.nickname = nickname;
		this.titleDispOoo = titleDispOoo;
		this.discontinued = discontinued;
		this.invitedInAs = invitedInAs;
		this.invitedInAsStartDate = invitedInAsStartDate;
		this.invitedInAsEndDate = invitedInAsEndDate;
		this.dispForOoOrdering = dispForOoOrdering;
		this.prodTrkPath = prodTrkPath;
		this.perFreeAccessToArtToCoau = perFreeAccessToArtToCoau;
		this.allwCoauSeeArtPrdStages = allwCoauSeeArtPrdStages;
		this.perCoauToSubsReviewProofs = perCoauToSubsReviewProofs;
		this.allowToAddColleagues = allowToAddColleagues;
		this.allowArticlesPrdNonprdPath = allowArticlesPrdNonprdPath;
		this.collecAConfliOfIntrstForm = collecAConfliOfIntrstForm;
		this.coauthReceiveInvitation = coauthReceiveInvitation;
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
		this.perFreeAccessArtToCorau = perFreeAccessArtToCorau;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.articleses = articleses;
		this.userPreferredJournalses = userPreferredJournalses;
		this.journalAlertses = journalAlertses;
	}

	@Id
	@Column(name = "JOURNAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getJournalId() {
		return this.journalId;
	}

	public void setJournalId(Integer journalId) {
		this.journalId = journalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "DH_ID", precision = 22, scale = 0)
	public Integer getDhId() {
		return this.dhId;
	}

	public void setDhId(Integer dhId) {
		this.dhId = dhId;
	}

	@Column(name = "SETUP_STATE_IN_AS", length = 100)
	public String getSetupStateInAs() {
		return this.setupStateInAs;
	}

	public void setSetupStateInAs(String setupStateInAs) {
		this.setupStateInAs = setupStateInAs;
	}

	@Column(name = "NICKNAME", length = 250)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "TITLE_DISP_OOO", length = 250)
	public String getTitleDispOoo() {
		return this.titleDispOoo;
	}

	public void setTitleDispOoo(String titleDispOoo) {
		this.titleDispOoo = titleDispOoo;
	}

	@Column(name = "DISCONTINUED", length = 1)
	public Character getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(Character discontinued) {
		this.discontinued = discontinued;
	}

	@Column(name = "INVITED_IN_AS", length = 1)
	public Character getInvitedInAs() {
		return this.invitedInAs;
	}

	public void setInvitedInAs(Character invitedInAs) {
		this.invitedInAs = invitedInAs;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVITED_IN_AS_START_DATE", length = 7)
	public Date getInvitedInAsStartDate() {
		return this.invitedInAsStartDate;
	}

	public void setInvitedInAsStartDate(Date invitedInAsStartDate) {
		this.invitedInAsStartDate = invitedInAsStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVITED_IN_AS_END_DATE", length = 7)
	public Date getInvitedInAsEndDate() {
		return this.invitedInAsEndDate;
	}

	public void setInvitedInAsEndDate(Date invitedInAsEndDate) {
		this.invitedInAsEndDate = invitedInAsEndDate;
	}

	@Column(name = "DISP_FOR_OO_ORDERING", length = 1)
	public Character getDispForOoOrdering() {
		return this.dispForOoOrdering;
	}

	public void setDispForOoOrdering(Character dispForOoOrdering) {
		this.dispForOoOrdering = dispForOoOrdering;
	}

	@Column(name = "PROD_TRK_PATH", length = 1)
	public Character getProdTrkPath() {
		return this.prodTrkPath;
	}

	public void setProdTrkPath(Character prodTrkPath) {
		this.prodTrkPath = prodTrkPath;
	}

	@Column(name = "PER_FREE_ACCESS_TO_ART_TO_COAU", length = 1)
	public Character getPerFreeAccessToArtToCoau() {
		return this.perFreeAccessToArtToCoau;
	}

	public void setPerFreeAccessToArtToCoau(Character perFreeAccessToArtToCoau) {
		this.perFreeAccessToArtToCoau = perFreeAccessToArtToCoau;
	}

	@Column(name = "ALLW_COAU_SEE_ART_PRD_STAGES", length = 1)
	public Character getAllwCoauSeeArtPrdStages() {
		return this.allwCoauSeeArtPrdStages;
	}

	public void setAllwCoauSeeArtPrdStages(Character allwCoauSeeArtPrdStages) {
		this.allwCoauSeeArtPrdStages = allwCoauSeeArtPrdStages;
	}

	@Column(name = "PER_COAU_TO_SUBS_REVIEW_PROOFS", length = 1)
	public Character getPerCoauToSubsReviewProofs() {
		return this.perCoauToSubsReviewProofs;
	}

	public void setPerCoauToSubsReviewProofs(Character perCoauToSubsReviewProofs) {
		this.perCoauToSubsReviewProofs = perCoauToSubsReviewProofs;
	}

	@Column(name = "ALLOW_TO_ADD_COLLEAGUES", length = 1)
	public Character getAllowToAddColleagues() {
		return this.allowToAddColleagues;
	}

	public void setAllowToAddColleagues(Character allowToAddColleagues) {
		this.allowToAddColleagues = allowToAddColleagues;
	}

	@Column(name = "ALLOW_ARTICLES_PRD_NONPRD_PATH", length = 1)
	public Character getAllowArticlesPrdNonprdPath() {
		return this.allowArticlesPrdNonprdPath;
	}

	public void setAllowArticlesPrdNonprdPath(
			Character allowArticlesPrdNonprdPath) {
		this.allowArticlesPrdNonprdPath = allowArticlesPrdNonprdPath;
	}

	@Column(name = "COLLEC_A_CONFLI_OF_INTRST_FORM", length = 1)
	public Character getCollecAConfliOfIntrstForm() {
		return this.collecAConfliOfIntrstForm;
	}

	public void setCollecAConfliOfIntrstForm(Character collecAConfliOfIntrstForm) {
		this.collecAConfliOfIntrstForm = collecAConfliOfIntrstForm;
	}

	@Column(name = "COAUTH_RECEIVE_INVITATION", length = 1)
	public Character getCoauthReceiveInvitation() {
		return this.coauthReceiveInvitation;
	}

	public void setCoauthReceiveInvitation(Character coauthReceiveInvitation) {
		this.coauthReceiveInvitation = coauthReceiveInvitation;
	}

	@Column(name = "DISP_OR_EMAIL_MRKTNG_TO_USR", length = 1)
	public Character getDispOrEmailMrktngToUsr() {
		return this.dispOrEmailMrktngToUsr;
	}

	public void setDispOrEmailMrktngToUsr(Character dispOrEmailMrktngToUsr) {
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
	}

	@Column(name = "DISP_OR_EMAIL_SURVEY_TO_USR", length = 1)
	public Character getDispOrEmailSurveyToUsr() {
		return this.dispOrEmailSurveyToUsr;
	}

	public void setDispOrEmailSurveyToUsr(Character dispOrEmailSurveyToUsr) {
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
	}

	@Column(name = "PER_FREE_ACCESS_ART_TO_CORAU", length = 1)
	public Character getPerFreeAccessArtToCorau() {
		return this.perFreeAccessArtToCorau;
	}

	public void setPerFreeAccessArtToCorau(Character perFreeAccessArtToCorau) {
		this.perFreeAccessArtToCorau = perFreeAccessArtToCorau;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journals")
	public Set<Articles> getArticleses() {
		return this.articleses;
	}

	public void setArticleses(Set<Articles> articleses) {
		this.articleses = articleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journals")
	public Set<UserPreferredJournals> getUserPreferredJournalses() {
		return this.userPreferredJournalses;
	}

	public void setUserPreferredJournalses(
			Set<UserPreferredJournals> userPreferredJournalses) {
		this.userPreferredJournalses = userPreferredJournalses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journals")
	public Set<JournalAlerts> getJournalAlertses() {
		return this.journalAlertses;
	}

	public void setJournalAlertses(Set<JournalAlerts> journalAlertses) {
		this.journalAlertses = journalAlertses;
	}

}
