package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 16, 2015 3:47:59 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JournalSetupStates generated by hbm2java
 */
@Entity
@Table(name = "journal_setup_states", catalog = "as2_app_db")
public class JournalSetupStates implements java.io.Serializable {

	private String setupStateCd;
	private String setupStateName;
	private Date createdDate;
	private byte[] createdBy;
	private Date updatedDate;
	private byte[] updatedBy;
	private Set<JournalConfiguration> journalConfigurations = new HashSet<JournalConfiguration>(
			0);

	public JournalSetupStates() {
	}

	public JournalSetupStates(String setupStateCd) {
		this.setupStateCd = setupStateCd;
	}

	public JournalSetupStates(String setupStateCd, String setupStateName,
			Date createdDate, byte[] createdBy, Date updatedDate,
			byte[] updatedBy, Set<JournalConfiguration> journalConfigurations) {
		this.setupStateCd = setupStateCd;
		this.setupStateName = setupStateName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.journalConfigurations = journalConfigurations;
	}

	@Id
	@Column(name = "SETUP_STATE_CD", unique = true, nullable = false, length = 15)
	public String getSetupStateCd() {
		return this.setupStateCd;
	}

	public void setSetupStateCd(String setupStateCd) {
		this.setupStateCd = setupStateCd;
	}

	@Column(name = "SETUP_STATE_NAME", length = 250)
	public String getSetupStateName() {
		return this.setupStateName;
	}

	public void setSetupStateName(String setupStateName) {
		this.setupStateName = setupStateName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "journalSetupStates")
	public Set<JournalConfiguration> getJournalConfigurations() {
		return this.journalConfigurations;
	}

	public void setJournalConfigurations(
			Set<JournalConfiguration> journalConfigurations) {
		this.journalConfigurations = journalConfigurations;
	}

}
