package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 23, 2015 2:35:20 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JournalAlerts generated by hbm2java
 */
@Entity
@Table(name = "JOURNAL_ALERTS")
public class JournalAlerts implements java.io.Serializable {

	private Integer jouAlertId;
	private Alerts alerts;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Integer journalId;
	private Character alertCdFlg;
	private Date createdDate;
	private Date updatedDate;

	public JournalAlerts() {
	}

	public JournalAlerts(Integer jouAlertId) {
		this.jouAlertId = jouAlertId;
	}

	public JournalAlerts(Integer jouAlertId, Alerts alerts,
			Users usersByCreatedBy, Users usersByUpdatedBy, Integer journalId,
			Character alertCdFlg, Date createdDate, Date updatedDate) {
		this.jouAlertId = jouAlertId;
		this.alerts = alerts;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.journalId = journalId;
		this.alertCdFlg = alertCdFlg;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "JOU_ALERT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getJouAlertId() {
		return this.jouAlertId;
	}

	public void setJouAlertId(Integer jouAlertId) {
		this.jouAlertId = jouAlertId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALERT_CD")
	public Alerts getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Alerts alerts) {
		this.alerts = alerts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "JOURNAL_ID", precision = 22, scale = 0)
	public Integer getJournalId() {
		return this.journalId;
	}

	public void setJournalId(Integer journalId) {
		this.journalId = journalId;
	}

	@Column(name = "ALERT_CD_FLG", length = 1)
	public Character getAlertCdFlg() {
		return this.alertCdFlg;
	}

	public void setAlertCdFlg(Character alertCdFlg) {
		this.alertCdFlg = alertCdFlg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
