package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 22, 2015 4:46:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JournalConfiguration generated by hbm2java
 */
@Entity
@Table(name = "journal_configuration", catalog = "as2_app_db")
public class JournalConfiguration implements java.io.Serializable {

	private long dhId;
	private JournalSetupStates journalSetupStates;
	private String nickname;
	private String titleDispOoo;
	private Boolean invitedInAs;
	private Date invitedInAsStartDate;
	private Date invitedInAsEndDate;
	private Boolean dispForOoOrdering;
	private Boolean prodTrkPath;
	private Boolean coauthCanHaveFreeAccArt;
	private Boolean coauthCanSeeArtProdStages;
	private Boolean coauthCanSubstReviewProofs;
	private Boolean collgCanViewArtWol;
	private Boolean artCanHavePrdNonprdPath;
	private Boolean canCollConflIntrstForms;
	private Boolean coauthReceiveInvitation;
	private Boolean dispOrEmailMrktngToUsr;
	private Boolean dispOrEmailSurveyToUsr;
	private Boolean corrauCanHaveFreeAccArt;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public JournalConfiguration() {
	}

	public JournalConfiguration(long dhId) {
		this.dhId = dhId;
	}

	public JournalConfiguration(long dhId,
			JournalSetupStates journalSetupStates, String nickname,
			String titleDispOoo, Boolean invitedInAs,
			Date invitedInAsStartDate, Date invitedInAsEndDate,
			Boolean dispForOoOrdering, Boolean prodTrkPath,
			Boolean coauthCanHaveFreeAccArt, Boolean coauthCanSeeArtProdStages,
			Boolean coauthCanSubstReviewProofs, Boolean collgCanViewArtWol,
			Boolean artCanHavePrdNonprdPath, Boolean canCollConflIntrstForms,
			Boolean coauthReceiveInvitation, Boolean dispOrEmailMrktngToUsr,
			Boolean dispOrEmailSurveyToUsr, Boolean corrauCanHaveFreeAccArt,
			Date createdDate, Long createdBy, Date updatedDate, Long updatedBy) {
		this.dhId = dhId;
		this.journalSetupStates = journalSetupStates;
		this.nickname = nickname;
		this.titleDispOoo = titleDispOoo;
		this.invitedInAs = invitedInAs;
		this.invitedInAsStartDate = invitedInAsStartDate;
		this.invitedInAsEndDate = invitedInAsEndDate;
		this.dispForOoOrdering = dispForOoOrdering;
		this.prodTrkPath = prodTrkPath;
		this.coauthCanHaveFreeAccArt = coauthCanHaveFreeAccArt;
		this.coauthCanSeeArtProdStages = coauthCanSeeArtProdStages;
		this.coauthCanSubstReviewProofs = coauthCanSubstReviewProofs;
		this.collgCanViewArtWol = collgCanViewArtWol;
		this.artCanHavePrdNonprdPath = artCanHavePrdNonprdPath;
		this.canCollConflIntrstForms = canCollConflIntrstForms;
		this.coauthReceiveInvitation = coauthReceiveInvitation;
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
		this.corrauCanHaveFreeAccArt = corrauCanHaveFreeAccArt;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "DH_ID", unique = true, nullable = false)
	public long getDhId() {
		return this.dhId;
	}

	public void setDhId(long dhId) {
		this.dhId = dhId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SETUP_STATE_CD_IN_AS")
	public JournalSetupStates getJournalSetupStates() {
		return this.journalSetupStates;
	}

	public void setJournalSetupStates(JournalSetupStates journalSetupStates) {
		this.journalSetupStates = journalSetupStates;
	}

	@Column(name = "NICKNAME", length = 250)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "TITLE_DISP_OOO", length = 250)
	public String getTitleDispOoo() {
		return this.titleDispOoo;
	}

	public void setTitleDispOoo(String titleDispOoo) {
		this.titleDispOoo = titleDispOoo;
	}

	@Column(name = "INVITED_IN_AS", length = 1)
	public Boolean getInvitedInAs() {
		return this.invitedInAs;
	}

	public void setInvitedInAs(Boolean invitedInAs) {
		this.invitedInAs = invitedInAs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INVITED_IN_AS_START_DATE", length = 19)
	public Date getInvitedInAsStartDate() {
		return this.invitedInAsStartDate;
	}

	public void setInvitedInAsStartDate(Date invitedInAsStartDate) {
		this.invitedInAsStartDate = invitedInAsStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INVITED_IN_AS_END_DATE", length = 19)
	public Date getInvitedInAsEndDate() {
		return this.invitedInAsEndDate;
	}

	public void setInvitedInAsEndDate(Date invitedInAsEndDate) {
		this.invitedInAsEndDate = invitedInAsEndDate;
	}

	@Column(name = "DISP_FOR_OO_ORDERING", length = 1)
	public Boolean getDispForOoOrdering() {
		return this.dispForOoOrdering;
	}

	public void setDispForOoOrdering(Boolean dispForOoOrdering) {
		this.dispForOoOrdering = dispForOoOrdering;
	}

	@Column(name = "PROD_TRK_PATH", length = 1)
	public Boolean getProdTrkPath() {
		return this.prodTrkPath;
	}

	public void setProdTrkPath(Boolean prodTrkPath) {
		this.prodTrkPath = prodTrkPath;
	}

	@Column(name = "COAUTH_CAN_HAVE_FREE_ACC_ART", length = 1)
	public Boolean getCoauthCanHaveFreeAccArt() {
		return this.coauthCanHaveFreeAccArt;
	}

	public void setCoauthCanHaveFreeAccArt(Boolean coauthCanHaveFreeAccArt) {
		this.coauthCanHaveFreeAccArt = coauthCanHaveFreeAccArt;
	}

	@Column(name = "COAUTH_CAN_SEE_ART_PROD_STAGES", length = 1)
	public Boolean getCoauthCanSeeArtProdStages() {
		return this.coauthCanSeeArtProdStages;
	}

	public void setCoauthCanSeeArtProdStages(Boolean coauthCanSeeArtProdStages) {
		this.coauthCanSeeArtProdStages = coauthCanSeeArtProdStages;
	}

	@Column(name = "COAUTH_CAN_SUBST_REVIEW_PROOFS", length = 1)
	public Boolean getCoauthCanSubstReviewProofs() {
		return this.coauthCanSubstReviewProofs;
	}

	public void setCoauthCanSubstReviewProofs(Boolean coauthCanSubstReviewProofs) {
		this.coauthCanSubstReviewProofs = coauthCanSubstReviewProofs;
	}

	@Column(name = "COLLG_CAN_VIEW_ART_WOL", length = 1)
	public Boolean getCollgCanViewArtWol() {
		return this.collgCanViewArtWol;
	}

	public void setCollgCanViewArtWol(Boolean collgCanViewArtWol) {
		this.collgCanViewArtWol = collgCanViewArtWol;
	}

	@Column(name = "ART_CAN_HAVE_PRD_NONPRD_PATH", length = 1)
	public Boolean getArtCanHavePrdNonprdPath() {
		return this.artCanHavePrdNonprdPath;
	}

	public void setArtCanHavePrdNonprdPath(Boolean artCanHavePrdNonprdPath) {
		this.artCanHavePrdNonprdPath = artCanHavePrdNonprdPath;
	}

	@Column(name = "CAN_COLL_CONFL_INTRST_FORMS", length = 1)
	public Boolean getCanCollConflIntrstForms() {
		return this.canCollConflIntrstForms;
	}

	public void setCanCollConflIntrstForms(Boolean canCollConflIntrstForms) {
		this.canCollConflIntrstForms = canCollConflIntrstForms;
	}

	@Column(name = "COAUTH_RECEIVE_INVITATION", length = 1)
	public Boolean getCoauthReceiveInvitation() {
		return this.coauthReceiveInvitation;
	}

	public void setCoauthReceiveInvitation(Boolean coauthReceiveInvitation) {
		this.coauthReceiveInvitation = coauthReceiveInvitation;
	}

	@Column(name = "DISP_OR_EMAIL_MRKTNG_TO_USR", length = 1)
	public Boolean getDispOrEmailMrktngToUsr() {
		return this.dispOrEmailMrktngToUsr;
	}

	public void setDispOrEmailMrktngToUsr(Boolean dispOrEmailMrktngToUsr) {
		this.dispOrEmailMrktngToUsr = dispOrEmailMrktngToUsr;
	}

	@Column(name = "DISP_OR_EMAIL_SURVEY_TO_USR", length = 1)
	public Boolean getDispOrEmailSurveyToUsr() {
		return this.dispOrEmailSurveyToUsr;
	}

	public void setDispOrEmailSurveyToUsr(Boolean dispOrEmailSurveyToUsr) {
		this.dispOrEmailSurveyToUsr = dispOrEmailSurveyToUsr;
	}

	@Column(name = "CORRAU_CAN_HAVE_FREE_ACC_ART", length = 1)
	public Boolean getCorrauCanHaveFreeAccArt() {
		return this.corrauCanHaveFreeAccArt;
	}

	public void setCorrauCanHaveFreeAccArt(Boolean corrauCanHaveFreeAccArt) {
		this.corrauCanHaveFreeAccArt = corrauCanHaveFreeAccArt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
