package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LicenseRejectionReasons generated by hbm2java
 */
@Entity
@Table(name = "license_rejection_reasons", catalog = "as2_app_db")
public class LicenseRejectionReasons implements java.io.Serializable {

	private String reasonCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String reasonText;
	private String reasonDescription;
	private Date createdDate;
	private Date updatedDate;
	private Set<RejectedLicenseDetails> rejectedLicenseDetailses = new HashSet<RejectedLicenseDetails>(
			0);

	public LicenseRejectionReasons() {
	}

	public LicenseRejectionReasons(String reasonCd) {
		this.reasonCd = reasonCd;
	}

	public LicenseRejectionReasons(String reasonCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String reasonText,
			String reasonDescription, Date createdDate, Date updatedDate,
			Set<RejectedLicenseDetails> rejectedLicenseDetailses) {
		this.reasonCd = reasonCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.reasonText = reasonText;
		this.reasonDescription = reasonDescription;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.rejectedLicenseDetailses = rejectedLicenseDetailses;
	}

	@Id
	@Column(name = "REASON_CD", unique = true, nullable = false, length = 15)
	public String getReasonCd() {
		return this.reasonCd;
	}

	public void setReasonCd(String reasonCd) {
		this.reasonCd = reasonCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "REASON_TEXT", length = 100)
	public String getReasonText() {
		return this.reasonText;
	}

	public void setReasonText(String reasonText) {
		this.reasonText = reasonText;
	}

	@Column(name = "REASON_DESCRIPTION", length = 3000)
	public String getReasonDescription() {
		return this.reasonDescription;
	}

	public void setReasonDescription(String reasonDescription) {
		this.reasonDescription = reasonDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "licenseRejectionReasons")
	public Set<RejectedLicenseDetails> getRejectedLicenseDetailses() {
		return this.rejectedLicenseDetailses;
	}

	public void setRejectedLicenseDetailses(
			Set<RejectedLicenseDetails> rejectedLicenseDetailses) {
		this.rejectedLicenseDetailses = rejectedLicenseDetailses;
	}

}
