package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Aug 5, 2015 12:05:24 PM by Hibernate Tools 4.0.0

import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LicenseUploadDetails generated by hbm2java
 */
@Entity
@Table(name = "LICENSE_UPLOAD_DETAILS")
public class LicenseUploadDetails implements java.io.Serializable {

	private Integer uploadId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private SavedLicenses savedLicenses;
	private Blob licenseFile;
	private Date createdDate;
	private Date updatedDate;

	public LicenseUploadDetails() {
	}

	public LicenseUploadDetails(Integer uploadId) {
		this.uploadId = uploadId;
	}

	public LicenseUploadDetails(Integer uploadId, Users usersByCreatedBy,
			Users usersByUpdatedBy, SavedLicenses savedLicenses,
			Blob licenseFile, Date createdDate, Date updatedDate) {
		this.uploadId = uploadId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.savedLicenses = savedLicenses;
		this.licenseFile = licenseFile;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "UPLOAD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUploadId() {
		return this.uploadId;
	}

	public void setUploadId(Integer uploadId) {
		this.uploadId = uploadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LICENSE_ID")
	public SavedLicenses getSavedLicenses() {
		return this.savedLicenses;
	}

	public void setSavedLicenses(SavedLicenses savedLicenses) {
		this.savedLicenses = savedLicenses;
	}

	@Column(name = "LICENSE_FILE")
	public Blob getLicenseFile() {
		return this.licenseFile;
	}

	public void setLicenseFile(Blob licenseFile) {
		this.licenseFile = licenseFile;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
