package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LockedAccountDetails generated by hbm2java
 */
public class LockedAccountDetails implements java.io.Serializable {

	private String userId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Long invalidLoginCount;
	private Date lockedTime;
	private String appKey;
	private Date loginAttemptTime;
	private Date createdDate;
	private Date updatedDate;

	public LockedAccountDetails() {
	}

	public LockedAccountDetails(String userId) {
		this.userId = userId;
	}

	public LockedAccountDetails(String userId, Users usersByCreatedBy,
			Users usersByUpdatedBy, Long invalidLoginCount, Date lockedTime,
			String appKey, Date loginAttemptTime, Date createdDate,
			Date updatedDate) {
		this.userId = userId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.invalidLoginCount = invalidLoginCount;
		this.lockedTime = lockedTime;
		this.appKey = appKey;
		this.loginAttemptTime = loginAttemptTime;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Long getInvalidLoginCount() {
		return this.invalidLoginCount;
	}

	public void setInvalidLoginCount(Long invalidLoginCount) {
		this.invalidLoginCount = invalidLoginCount;
	}

	public Date getLockedTime() {
		return this.lockedTime;
	}

	public void setLockedTime(Date lockedTime) {
		this.lockedTime = lockedTime;
	}

	public String getAppKey() {
		return this.appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	public Date getLoginAttemptTime() {
		return this.loginAttemptTime;
	}

	public void setLoginAttemptTime(Date loginAttemptTime) {
		this.loginAttemptTime = loginAttemptTime;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
