package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ObjectTypes generated by hbm2java
 */
public class ObjectTypes implements java.io.Serializable {

	private String objectTypeCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String objectType;
	private Date createdDate;
	private Date updatedDate;
	private Set<AdditionalPermissions> additionalPermissionses = new HashSet<AdditionalPermissions>(
			0);
	private Set<AuditDetails> auditDetailses = new HashSet<AuditDetails>(0);

	public ObjectTypes() {
	}

	public ObjectTypes(String objectTypeCd) {
		this.objectTypeCd = objectTypeCd;
	}

	public ObjectTypes(String objectTypeCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String objectType, Date createdDate,
			Date updatedDate,
			Set<AdditionalPermissions> additionalPermissionses,
			Set<AuditDetails> auditDetailses) {
		this.objectTypeCd = objectTypeCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.objectType = objectType;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.additionalPermissionses = additionalPermissionses;
		this.auditDetailses = auditDetailses;
	}

	public String getObjectTypeCd() {
		return this.objectTypeCd;
	}

	public void setObjectTypeCd(String objectTypeCd) {
		this.objectTypeCd = objectTypeCd;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<AdditionalPermissions> getAdditionalPermissionses() {
		return this.additionalPermissionses;
	}

	public void setAdditionalPermissionses(
			Set<AdditionalPermissions> additionalPermissionses) {
		this.additionalPermissionses = additionalPermissionses;
	}

	public Set<AuditDetails> getAuditDetailses() {
		return this.auditDetailses;
	}

	public void setAuditDetailses(Set<AuditDetails> auditDetailses) {
		this.auditDetailses = auditDetailses;
	}

}
