package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjectTypes generated by hbm2java
 */
@Entity
@Table(name = "object_types", catalog = "as2_app_db")
public class ObjectTypes implements java.io.Serializable {

	private String objectTypeCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String objectType;
	private Date createdDate;
	private Date updatedDate;
	private Set<AdditionalPermissions> additionalPermissionses = new HashSet<AdditionalPermissions>(
			0);
	private Set<AuditDetails> auditDetailses = new HashSet<AuditDetails>(0);

	public ObjectTypes() {
	}

	public ObjectTypes(String objectTypeCd) {
		this.objectTypeCd = objectTypeCd;
	}

	public ObjectTypes(String objectTypeCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String objectType, Date createdDate,
			Date updatedDate,
			Set<AdditionalPermissions> additionalPermissionses,
			Set<AuditDetails> auditDetailses) {
		this.objectTypeCd = objectTypeCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.objectType = objectType;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.additionalPermissionses = additionalPermissionses;
		this.auditDetailses = auditDetailses;
	}

	@Id
	@Column(name = "OBJECT_TYPE_CD", unique = true, nullable = false, length = 15)
	public String getObjectTypeCd() {
		return this.objectTypeCd;
	}

	public void setObjectTypeCd(String objectTypeCd) {
		this.objectTypeCd = objectTypeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "OBJECT_TYPE", length = 50)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectTypes")
	public Set<AdditionalPermissions> getAdditionalPermissionses() {
		return this.additionalPermissionses;
	}

	public void setAdditionalPermissionses(
			Set<AdditionalPermissions> additionalPermissionses) {
		this.additionalPermissionses = additionalPermissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectTypes")
	public Set<AuditDetails> getAuditDetailses() {
		return this.auditDetailses;
	}

	public void setAuditDetailses(Set<AuditDetails> auditDetailses) {
		this.auditDetailses = auditDetailses;
	}

}
