package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 23, 2015 2:35:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "ORDERS")
public class Orders implements java.io.Serializable {

	private Integer orderId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Integer articleAuthId;
	private String orderType;
	private String ooOaFlg;
	private String orderStatus;
	private Integer downstreamappOrderId;
	private Date createdDate;
	private Date updatedDate;

	public Orders() {
	}

	public Orders(Integer orderId) {
		this.orderId = orderId;
	}

	public Orders(Integer orderId, Users usersByCreatedBy,
			Users usersByUpdatedBy, Integer articleAuthId, String orderType,
			String ooOaFlg, String orderStatus, Integer downstreamappOrderId,
			Date createdDate, Date updatedDate) {
		this.orderId = orderId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.articleAuthId = articleAuthId;
		this.orderType = orderType;
		this.ooOaFlg = ooOaFlg;
		this.orderStatus = orderStatus;
		this.downstreamappOrderId = downstreamappOrderId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "ORDER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="ORDERS_SEQ")
    @SequenceGenerator(name="ORDERS_SEQ",sequenceName="ORDERS_SEQ",allocationSize=1)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "ARTICLE_AUTH_ID", precision = 22, scale = 0)
	public Integer getArticleAuthId() {
		return this.articleAuthId;
	}

	public void setArticleAuthId(Integer articleAuthId) {
		this.articleAuthId = articleAuthId;
	}

	@Column(name = "ORDER_TYPE", length = 15)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "OO_OA_FLG", length = 2)
	public String getOoOaFlg() {
		return this.ooOaFlg;
	}

	public void setOoOaFlg(String ooOaFlg) {
		this.ooOaFlg = ooOaFlg;
	}

	@Column(name = "ORDER_STATUS", length = 25)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "DOWNSTREAMAPP_ORDER_ID", precision = 22, scale = 0)
	public Integer getDownstreamappOrderId() {
		return this.downstreamappOrderId;
	}

	public void setDownstreamappOrderId(Integer downstreamappOrderId) {
		this.downstreamappOrderId = downstreamappOrderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
