package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 22, 2015 4:46:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderReference generated by hbm2java
 */
@Entity
@Table(name = "order_reference", catalog = "as2_app_db")
public class OrderReference implements java.io.Serializable {

	private long orderId;
	private Long oouniqueId;
	private Long ecoreSubscriptionNum;
	private Long ecoreSequenceNum;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public OrderReference() {
	}

	public OrderReference(long orderId) {
		this.orderId = orderId;
	}

	public OrderReference(long orderId, Long oouniqueId,
			Long ecoreSubscriptionNum, Long ecoreSequenceNum, Date createdDate,
			Long createdBy, Date updatedDate, Long updatedBy) {
		this.orderId = orderId;
		this.oouniqueId = oouniqueId;
		this.ecoreSubscriptionNum = ecoreSubscriptionNum;
		this.ecoreSequenceNum = ecoreSequenceNum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "OOUNIQUE_ID")
	public Long getOouniqueId() {
		return this.oouniqueId;
	}

	public void setOouniqueId(Long oouniqueId) {
		this.oouniqueId = oouniqueId;
	}

	@Column(name = "ECORE_SUBSCRIPTION_NUM")
	public Long getEcoreSubscriptionNum() {
		return this.ecoreSubscriptionNum;
	}

	public void setEcoreSubscriptionNum(Long ecoreSubscriptionNum) {
		this.ecoreSubscriptionNum = ecoreSubscriptionNum;
	}

	@Column(name = "ECORE_SEQUENCE_NUM")
	public Long getEcoreSequenceNum() {
		return this.ecoreSequenceNum;
	}

	public void setEcoreSequenceNum(Long ecoreSequenceNum) {
		this.ecoreSequenceNum = ecoreSequenceNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
