package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OwnershipTypes generated by hbm2java
 */
@Entity
@Table(name = "ownership_types", catalog = "as2_app_db")
public class OwnershipTypes implements java.io.Serializable {

	private String typeCd;
	private String typeName;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;
	private Set<SubOwnershipTypes> subOwnershipTypeses = new HashSet<SubOwnershipTypes>(
			0);

	public OwnershipTypes() {
	}

	public OwnershipTypes(String typeCd) {
		this.typeCd = typeCd;
	}

	public OwnershipTypes(String typeCd, String typeName, Date createdDate,
			UUID createdBy, Date updatedDate, UUID updatedBy,
			Set<SubOwnershipTypes> subOwnershipTypeses) {
		this.typeCd = typeCd;
		this.typeName = typeName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.subOwnershipTypeses = subOwnershipTypeses;
	}

	@Id
	@Column(name = "TYPE_CD", unique = true, nullable = false, length = 25)
	public String getTypeCd() {
		return this.typeCd;
	}

	public void setTypeCd(String typeCd) {
		this.typeCd = typeCd;
	}

	@Column(name = "TYPE_NAME", length = 250)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ownershipTypes")
	public Set<SubOwnershipTypes> getSubOwnershipTypeses() {
		return this.subOwnershipTypeses;
	}

	public void setSubOwnershipTypeses(
			Set<SubOwnershipTypes> subOwnershipTypeses) {
		this.subOwnershipTypeses = subOwnershipTypeses;
	}

}
