package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Aug 5, 2015 12:05:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OwnershipTypes generated by hbm2java
 */
@Entity
@Table(name = "OWNERSHIP_TYPES")
public class OwnershipTypes implements java.io.Serializable {

	private String typeCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String typeName;
	private Date createdDate;
	private Date updatedDate;
	private Set<SubOwnershipTypes> subOwnershipTypeses = new HashSet<SubOwnershipTypes>(
			0);

	public OwnershipTypes() {
	}

	public OwnershipTypes(String typeCd) {
		this.typeCd = typeCd;
	}

	public OwnershipTypes(String typeCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String typeName, Date createdDate,
			Date updatedDate, Set<SubOwnershipTypes> subOwnershipTypeses) {
		this.typeCd = typeCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.typeName = typeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.subOwnershipTypeses = subOwnershipTypeses;
	}

	@Id
	@Column(name = "TYPE_CD", unique = true, nullable = false, length = 25)
	public String getTypeCd() {
		return this.typeCd;
	}

	public void setTypeCd(String typeCd) {
		this.typeCd = typeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "TYPE_NAME", length = 250)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ownershipTypes")
	public Set<SubOwnershipTypes> getSubOwnershipTypeses() {
		return this.subOwnershipTypeses;
	}

	public void setSubOwnershipTypeses(
			Set<SubOwnershipTypes> subOwnershipTypeses) {
		this.subOwnershipTypeses = subOwnershipTypeses;
	}

}
