package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permissions generated by hbm2java
 */
public class Permissions implements java.io.Serializable {

	private String permissionCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String permissionName;
	private Date createdDate;
	private Date updatedDate;
	private Set<PermissionGroups> permissionGroupses = new HashSet<PermissionGroups>(
			0);
	private Set<RolePermissions> rolePermissionses = new HashSet<RolePermissions>(
			0);
	private Set<AdditionalPermissions> additionalPermissionses = new HashSet<AdditionalPermissions>(
			0);

	public Permissions() {
	}

	public Permissions(String permissionCd) {
		this.permissionCd = permissionCd;
	}

	public Permissions(String permissionCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String permissionName, Date createdDate,
			Date updatedDate, Set<PermissionGroups> permissionGroupses,
			Set<RolePermissions> rolePermissionses,
			Set<AdditionalPermissions> additionalPermissionses) {
		this.permissionCd = permissionCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.permissionName = permissionName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.permissionGroupses = permissionGroupses;
		this.rolePermissionses = rolePermissionses;
		this.additionalPermissionses = additionalPermissionses;
	}

	public String getPermissionCd() {
		return this.permissionCd;
	}

	public void setPermissionCd(String permissionCd) {
		this.permissionCd = permissionCd;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<PermissionGroups> getPermissionGroupses() {
		return this.permissionGroupses;
	}

	public void setPermissionGroupses(Set<PermissionGroups> permissionGroupses) {
		this.permissionGroupses = permissionGroupses;
	}

	public Set<RolePermissions> getRolePermissionses() {
		return this.rolePermissionses;
	}

	public void setRolePermissionses(Set<RolePermissions> rolePermissionses) {
		this.rolePermissionses = rolePermissionses;
	}

	public Set<AdditionalPermissions> getAdditionalPermissionses() {
		return this.additionalPermissionses;
	}

	public void setAdditionalPermissionses(
			Set<AdditionalPermissions> additionalPermissionses) {
		this.additionalPermissionses = additionalPermissionses;
	}

}
