package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 23, 2015 2:35:20 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductRelations generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_RELATIONS")
public class ProductRelations implements java.io.Serializable {

	private String dhTypeRelCd;
	private Products productsByChildDhId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products productsByParentDhId;
	private Date createdDate;
	private Date updatedDate;

	public ProductRelations() {
	}

	public ProductRelations(String dhTypeRelCd) {
		this.dhTypeRelCd = dhTypeRelCd;
	}

	public ProductRelations(String dhTypeRelCd, Products productsByChildDhId,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			Products productsByParentDhId, Date createdDate, Date updatedDate) {
		this.dhTypeRelCd = dhTypeRelCd;
		this.productsByChildDhId = productsByChildDhId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.productsByParentDhId = productsByParentDhId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "DH_TYPE_REL_CD", unique = true, nullable = false, length = 15)
	public String getDhTypeRelCd() {
		return this.dhTypeRelCd;
	}

	public void setDhTypeRelCd(String dhTypeRelCd) {
		this.dhTypeRelCd = dhTypeRelCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHILD_DH_ID")
	public Products getProductsByChildDhId() {
		return this.productsByChildDhId;
	}

	public void setProductsByChildDhId(Products productsByChildDhId) {
		this.productsByChildDhId = productsByChildDhId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_DH_ID")
	public Products getProductsByParentDhId() {
		return this.productsByParentDhId;
	}

	public void setProductsByParentDhId(Products productsByParentDhId) {
		this.productsByParentDhId = productsByParentDhId;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
