package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 12, 2015 11:27:32 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPublicationStatuses generated by hbm2java
 */
@Entity
@Table(name = "product_publication_statuses", catalog = "as2_app_db")
public class ProductPublicationStatuses implements java.io.Serializable {

	private Long productPubId;
	private PublicationStatuses publicationStatuses;
	private long dhId;
	private Date publicationStatusDate;
	private Date createdDate;
	private byte[] createdBy;
	private Date updatedDate;
	private byte[] updatedBy;

	public ProductPublicationStatuses() {
	}

	public ProductPublicationStatuses(long dhId) {
		this.dhId = dhId;
	}

	public ProductPublicationStatuses(PublicationStatuses publicationStatuses,
			long dhId, Date publicationStatusDate, Date createdDate,
			byte[] createdBy, Date updatedDate, byte[] updatedBy) {
		this.publicationStatuses = publicationStatuses;
		this.dhId = dhId;
		this.publicationStatusDate = publicationStatusDate;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PRODUCT_PUB_ID", unique = true, nullable = false)
	public Long getProductPubId() {
		return this.productPubId;
	}

	public void setProductPubId(Long productPubId) {
		this.productPubId = productPubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUBLICATION_STATUS_CD")
	public PublicationStatuses getPublicationStatuses() {
		return this.publicationStatuses;
	}

	public void setPublicationStatuses(PublicationStatuses publicationStatuses) {
		this.publicationStatuses = publicationStatuses;
	}

	@Column(name = "DH_ID", nullable = false)
	public long getDhId() {
		return this.dhId;
	}

	public void setDhId(long dhId) {
		this.dhId = dhId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUBLICATION_STATUS_DATE", length = 19)
	public Date getPublicationStatusDate() {
		return this.publicationStatusDate;
	}

	public void setPublicationStatusDate(Date publicationStatusDate) {
		this.publicationStatusDate = publicationStatusDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

}
