package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jun 23, 2015 2:35:20 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductTypes generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_TYPES")
public class ProductTypes implements java.io.Serializable {

	private String dhTypeCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String dhTypeName;
	private Date createdDate;
	private Date updatedDate;
	private Set<Products> productses = new HashSet<Products>(0);

	public ProductTypes() {
	}

	public ProductTypes(String dhTypeCd) {
		this.dhTypeCd = dhTypeCd;
	}

	public ProductTypes(String dhTypeCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String dhTypeName, Date createdDate,
			Date updatedDate, Set<Products> productses) {
		this.dhTypeCd = dhTypeCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.dhTypeName = dhTypeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.productses = productses;
	}

	@Id
	@Column(name = "DH_TYPE_CD", unique = true, nullable = false, length = 15)
	public String getDhTypeCd() {
		return this.dhTypeCd;
	}

	public void setDhTypeCd(String dhTypeCd) {
		this.dhTypeCd = dhTypeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "DH_TYPE_NAME", length = 25)
	public String getDhTypeName() {
		return this.dhTypeName;
	}

	public void setDhTypeName(String dhTypeName) {
		this.dhTypeName = dhTypeName;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productTypes")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
