package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ProductPersonRelations generated by hbm2java
 */
public class ProductPersonRelations implements java.io.Serializable {

	private Long prodRelationId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private UserProfile userProfile;
	private ProductRoles productRoles;
	private String emailAddr;
	private Date dateActivated;
	private Date updatedDate;

	public ProductPersonRelations() {
	}

	public ProductPersonRelations(Products products) {
		this.products = products;
	}

	public ProductPersonRelations(Users usersByCreatedBy,
			Users usersByUpdatedBy, Products products, UserProfile userProfile,
			ProductRoles productRoles, String emailAddr, Date dateActivated,
			Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.userProfile = userProfile;
		this.productRoles = productRoles;
		this.emailAddr = emailAddr;
		this.dateActivated = dateActivated;
		this.updatedDate = updatedDate;
	}

	public Long getProdRelationId() {
		return this.prodRelationId;
	}

	public void setProdRelationId(Long prodRelationId) {
		this.prodRelationId = prodRelationId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public ProductRoles getProductRoles() {
		return this.productRoles;
	}

	public void setProductRoles(ProductRoles productRoles) {
		this.productRoles = productRoles;
	}

	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	public Date getDateActivated() {
		return this.dateActivated;
	}

	public void setDateActivated(Date dateActivated) {
		this.dateActivated = dateActivated;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
