package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPublicationStatuses generated by hbm2java
 */
@Entity
@Table(name = "product_publication_statuses", catalog = "as2_app_db")
public class ProductPublicationStatuses implements java.io.Serializable {

	private Long productPubId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private PublicationStatuses publicationStatuses;
	private Date publicationStatusDate;
	private Date createdDate;
	private Date updatedDate;

	public ProductPublicationStatuses() {
	}

	public ProductPublicationStatuses(Products products) {
		this.products = products;
	}

	public ProductPublicationStatuses(Users usersByCreatedBy,
			Users usersByUpdatedBy, Products products,
			PublicationStatuses publicationStatuses,
			Date publicationStatusDate, Date createdDate, Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.publicationStatuses = publicationStatuses;
		this.publicationStatusDate = publicationStatusDate;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PRODUCT_PUB_ID", unique = true, nullable = false)
	public Long getProductPubId() {
		return this.productPubId;
	}

	public void setProductPubId(Long productPubId) {
		this.productPubId = productPubId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUBLICATION_STATUS_CD")
	public PublicationStatuses getPublicationStatuses() {
		return this.publicationStatuses;
	}

	public void setPublicationStatuses(PublicationStatuses publicationStatuses) {
		this.publicationStatuses = publicationStatuses;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUBLICATION_STATUS_DATE", length = 19)
	public Date getPublicationStatusDate() {
		return this.publicationStatusDate;
	}

	public void setPublicationStatusDate(Date publicationStatusDate) {
		this.publicationStatusDate = publicationStatusDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
