package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductPersonRelations generated by hbm2java
 */
@Entity
@Table(name = "product_person_relations", catalog = "as2_app_db")
public class ProductPersonRelations implements java.io.Serializable {

	private Long prodRelationId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private UserProfile userProfile;
	private ProductRoles productRoles;
	private String emailAddr;
	private Date dateActivated;
	private Date updatedDate;

	public ProductPersonRelations() {
	}

	public ProductPersonRelations(Products products) {
		this.products = products;
	}

	public ProductPersonRelations(Users usersByCreatedBy,
			Users usersByUpdatedBy, Products products, UserProfile userProfile,
			ProductRoles productRoles, String emailAddr, Date dateActivated,
			Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.userProfile = userProfile;
		this.productRoles = productRoles;
		this.emailAddr = emailAddr;
		this.dateActivated = dateActivated;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROD_RELATION_ID", unique = true, nullable = false)
	public Long getProdRelationId() {
		return this.prodRelationId;
	}

	public void setProdRelationId(Long prodRelationId) {
		this.prodRelationId = prodRelationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ROLE_CD")
	public ProductRoles getProductRoles() {
		return this.productRoles;
	}

	public void setProductRoles(ProductRoles productRoles) {
		this.productRoles = productRoles;
	}

	@Column(name = "EMAIL_ADDR", length = 100)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ACTIVATED", length = 19)
	public Date getDateActivated() {
		return this.dateActivated;
	}

	public void setDateActivated(Date dateActivated) {
		this.dateActivated = dateActivated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
