package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductRoles generated by hbm2java
 */
public class ProductRoles implements java.io.Serializable {

	private String productRoleCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String productRoleName;
	private String description;
	private Date createdDate;
	private Date updatedDate;
	private Set<ProductPersonRelations> productPersonRelationses = new HashSet<ProductPersonRelations>(
			0);

	public ProductRoles() {
	}

	public ProductRoles(String productRoleCd) {
		this.productRoleCd = productRoleCd;
	}

	public ProductRoles(String productRoleCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String productRoleName, String description,
			Date createdDate, Date updatedDate,
			Set<ProductPersonRelations> productPersonRelationses) {
		this.productRoleCd = productRoleCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.productRoleName = productRoleName;
		this.description = description;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.productPersonRelationses = productPersonRelationses;
	}

	public String getProductRoleCd() {
		return this.productRoleCd;
	}

	public void setProductRoleCd(String productRoleCd) {
		this.productRoleCd = productRoleCd;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getProductRoleName() {
		return this.productRoleName;
	}

	public void setProductRoleName(String productRoleName) {
		this.productRoleName = productRoleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<ProductPersonRelations> getProductPersonRelationses() {
		return this.productPersonRelationses;
	}

	public void setProductPersonRelationses(
			Set<ProductPersonRelations> productPersonRelationses) {
		this.productPersonRelationses = productPersonRelationses;
	}

}
