package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PublicationStatuses generated by hbm2java
 */
@Entity
@Table(name = "publication_statuses", catalog = "as2_app_db")
public class PublicationStatuses implements java.io.Serializable {

	private String publicationStatusCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String publicationStatusName;
	private Date createdDate;
	private Date updatedDate;
	private Set<ProductPublicationStatuses> productPublicationStatuseses = new HashSet<ProductPublicationStatuses>(
			0);

	public PublicationStatuses() {
	}

	public PublicationStatuses(String publicationStatusCd) {
		this.publicationStatusCd = publicationStatusCd;
	}

	public PublicationStatuses(String publicationStatusCd,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			String publicationStatusName, Date createdDate, Date updatedDate,
			Set<ProductPublicationStatuses> productPublicationStatuseses) {
		this.publicationStatusCd = publicationStatusCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.publicationStatusName = publicationStatusName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.productPublicationStatuseses = productPublicationStatuseses;
	}

	@Id
	@Column(name = "PUBLICATION_STATUS_CD", unique = true, nullable = false, length = 15)
	public String getPublicationStatusCd() {
		return this.publicationStatusCd;
	}

	public void setPublicationStatusCd(String publicationStatusCd) {
		this.publicationStatusCd = publicationStatusCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "PUBLICATION_STATUS_NAME", length = 250)
	public String getPublicationStatusName() {
		return this.publicationStatusName;
	}

	public void setPublicationStatusName(String publicationStatusName) {
		this.publicationStatusName = publicationStatusName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publicationStatuses")
	public Set<ProductPublicationStatuses> getProductPublicationStatuseses() {
		return this.productPublicationStatuseses;
	}

	public void setProductPublicationStatuseses(
			Set<ProductPublicationStatuses> productPublicationStatuseses) {
		this.productPublicationStatuseses = productPublicationStatuseses;
	}

}
