package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 29, 2015 12:48:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RejectedLicenseDetails generated by hbm2java
 */
@Entity
@Table(name = "rejected_license_details", catalog = "as2_app_db")
public class RejectedLicenseDetails implements java.io.Serializable {

	private Long rejectedId;
	private Long dhId;
	private String rejectionReasonCd;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public RejectedLicenseDetails() {
	}

	public RejectedLicenseDetails(Long dhId, String rejectionReasonCd,
			Date createdDate, Long createdBy, Date updatedDate, Long updatedBy) {
		this.dhId = dhId;
		this.rejectionReasonCd = rejectionReasonCd;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REJECTED_ID", unique = true, nullable = false)
	public Long getRejectedId() {
		return this.rejectedId;
	}

	public void setRejectedId(Long rejectedId) {
		this.rejectedId = rejectedId;
	}

	@Column(name = "DH_ID")
	public Long getDhId() {
		return this.dhId;
	}

	public void setDhId(Long dhId) {
		this.dhId = dhId;
	}

	@Column(name = "REJECTION_REASON_CD", length = 15)
	public String getRejectionReasonCd() {
		return this.rejectionReasonCd;
	}

	public void setRejectionReasonCd(String rejectionReasonCd) {
		this.rejectionReasonCd = rejectionReasonCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
