package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RejectedLicenseDetails generated by hbm2java
 */
@Entity
@Table(name = "rejected_license_details", catalog = "as2_app_db")
public class RejectedLicenseDetails implements java.io.Serializable {

	private Long rejectedId;
	private Users usersByCreatedBy;
	private LicenseRejectionReasons licenseRejectionReasons;
	private Users usersByUpdatedBy;
	private Products products;
	private Date createdDate;
	private Date updatedDate;

	public RejectedLicenseDetails() {
	}

	public RejectedLicenseDetails(Users usersByCreatedBy,
			LicenseRejectionReasons licenseRejectionReasons,
			Users usersByUpdatedBy, Products products, Date createdDate,
			Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.licenseRejectionReasons = licenseRejectionReasons;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REJECTED_ID", unique = true, nullable = false)
	public Long getRejectedId() {
		return this.rejectedId;
	}

	public void setRejectedId(Long rejectedId) {
		this.rejectedId = rejectedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REJECTION_REASON_CD")
	public LicenseRejectionReasons getLicenseRejectionReasons() {
		return this.licenseRejectionReasons;
	}

	public void setLicenseRejectionReasons(
			LicenseRejectionReasons licenseRejectionReasons) {
		this.licenseRejectionReasons = licenseRejectionReasons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
