package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchFunders generated by hbm2java
 */
public class ResearchFunders implements java.io.Serializable {

	private Long resfunderid;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String funderDoi;
	private String funderName;
	private Date createdDate;
	private Date updatedDate;
	private Set<UserFunders> userFunderses = new HashSet<UserFunders>(0);

	public ResearchFunders() {
	}

	public ResearchFunders(Users usersByCreatedBy, Users usersByUpdatedBy,
			String funderDoi, String funderName, Date createdDate,
			Date updatedDate, Set<UserFunders> userFunderses) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.funderDoi = funderDoi;
		this.funderName = funderName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.userFunderses = userFunderses;
	}

	public Long getResfunderid() {
		return this.resfunderid;
	}

	public void setResfunderid(Long resfunderid) {
		this.resfunderid = resfunderid;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getFunderDoi() {
		return this.funderDoi;
	}

	public void setFunderDoi(String funderDoi) {
		this.funderDoi = funderDoi;
	}

	public String getFunderName() {
		return this.funderName;
	}

	public void setFunderName(String funderName) {
		this.funderName = funderName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<UserFunders> getUserFunderses() {
		return this.userFunderses;
	}

	public void setUserFunderses(Set<UserFunders> userFunderses) {
		this.userFunderses = userFunderses;
	}

}
