package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

/**
 * RolePermissionsId generated by hbm2java
 */
public class RolePermissionsId implements java.io.Serializable {

	private long roleId;
	private String permissionCd;

	public RolePermissionsId() {
	}

	public RolePermissionsId(long roleId, String permissionCd) {
		this.roleId = roleId;
		this.permissionCd = permissionCd;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public String getPermissionCd() {
		return this.permissionCd;
	}

	public void setPermissionCd(String permissionCd) {
		this.permissionCd = permissionCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePermissionsId))
			return false;
		RolePermissionsId castOther = (RolePermissionsId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& ((this.getPermissionCd() == castOther.getPermissionCd()) || (this
						.getPermissionCd() != null
						&& castOther.getPermissionCd() != null && this
						.getPermissionCd().equals(castOther.getPermissionCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRoleId();
		result = 37
				* result
				+ (getPermissionCd() == null ? 0 : this.getPermissionCd()
						.hashCode());
		return result;
	}

}
