package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SavedLicenses generated by hbm2java
 */
@Entity
@Table(name = "saved_licenses", catalog = "as2_app_db")
public class SavedLicenses implements java.io.Serializable {

	private Long licenseId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private Users usersByUserId;
	private String licenseObject;
	private Date createdDate;
	private Date updatedDate;
	private Set<LicenseUploadDetails> licenseUploadDetailses = new HashSet<LicenseUploadDetails>(
			0);

	public SavedLicenses() {
	}

	public SavedLicenses(Users usersByCreatedBy, Users usersByUpdatedBy,
			Products products, Users usersByUserId, String licenseObject,
			Date createdDate, Date updatedDate,
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.usersByUserId = usersByUserId;
		this.licenseObject = licenseObject;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LICENSE_ID", unique = true, nullable = false)
	public Long getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Long licenseId) {
		this.licenseId = licenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@Column(name = "LICENSE_OBJECT", length = 65535)
	public String getLicenseObject() {
		return this.licenseObject;
	}

	public void setLicenseObject(String licenseObject) {
		this.licenseObject = licenseObject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "savedLicenses")
	public Set<LicenseUploadDetails> getLicenseUploadDetailses() {
		return this.licenseUploadDetailses;
	}

	public void setLicenseUploadDetailses(
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

}
