package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SavedLicenses generated by hbm2java
 */
@Entity
@Table(name = "saved_licenses", catalog = "as2_app_db")
public class SavedLicenses implements java.io.Serializable {

	private Long licenseId;
	private UUID participantId;
	private Long dhId;
	private byte[] licenseObject;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;
	private Set<LicenseUploadDetails> licenseUploadDetailses = new HashSet<LicenseUploadDetails>(
			0);

	public SavedLicenses() {
	}

	public SavedLicenses(UUID participantId, Long dhId, byte[] licenseObject,
			Date createdDate, UUID createdBy, Date updatedDate, UUID updatedBy,
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.participantId = participantId;
		this.dhId = dhId;
		this.licenseObject = licenseObject;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LICENSE_ID", unique = true, nullable = false)
	public Long getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Long licenseId) {
		this.licenseId = licenseId;
	}

	@Column(name = "participant_id")
	public UUID getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(UUID participantId) {
		this.participantId = participantId;
	}

	@Column(name = "DH_ID")
	public Long getDhId() {
		return this.dhId;
	}

	public void setDhId(Long dhId) {
		this.dhId = dhId;
	}

	@Column(name = "LICENSE_OBJECT")
	public byte[] getLicenseObject() {
		return this.licenseObject;
	}

	public void setLicenseObject(byte[] licenseObject) {
		this.licenseObject = licenseObject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "savedLicenses")
	public Set<LicenseUploadDetails> getLicenseUploadDetailses() {
		return this.licenseUploadDetailses;
	}

	public void setLicenseUploadDetailses(
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

}
