package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Aug 5, 2015 12:05:24 PM by Hibernate Tools 4.0.0

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SavedLicenses generated by hbm2java
 */
@Entity
@Table(name = "SAVED_LICENSES")
public class SavedLicenses implements java.io.Serializable {

	private Integer licenseId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private Users usersByUserId;
	private Clob licenseObject;
	private Date createdDate;
	private Date updatedDate;
	private Set<LicenseUploadDetails> licenseUploadDetailses = new HashSet<LicenseUploadDetails>(
			0);

	public SavedLicenses() {
	}

	public SavedLicenses(Integer licenseId) {
		this.licenseId = licenseId;
	}

	public SavedLicenses(Integer licenseId, Users usersByCreatedBy,
			Users usersByUpdatedBy, Products products, Users usersByUserId,
			Clob licenseObject, Date createdDate, Date updatedDate,
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.licenseId = licenseId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.usersByUserId = usersByUserId;
		this.licenseObject = licenseObject;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

	@Id
	@Column(name = "LICENSE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Integer licenseId) {
		this.licenseId = licenseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID")
	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	@Column(name = "LICENSE_OBJECT")
	public Clob getLicenseObject() {
		return this.licenseObject;
	}

	public void setLicenseObject(Clob licenseObject) {
		this.licenseObject = licenseObject;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "savedLicenses")
	public Set<LicenseUploadDetails> getLicenseUploadDetailses() {
		return this.licenseUploadDetailses;
	}

	public void setLicenseUploadDetailses(
			Set<LicenseUploadDetails> licenseUploadDetailses) {
		this.licenseUploadDetailses = licenseUploadDetailses;
	}

}
