package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SavedOrders generated by hbm2java
 */
@Entity
@Table(name = "saved_orders", catalog = "as2_app_db")
public class SavedOrders implements java.io.Serializable {

	private Long orderId;
	private Long dhId;
	private UUID participantId;
	private byte[] orderObject;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;

	public SavedOrders() {
	}

	public SavedOrders(Long dhId, UUID participantId, byte[] orderObject,
			Date createdDate, UUID createdBy, Date updatedDate, UUID updatedBy) {
		this.dhId = dhId;
		this.participantId = participantId;
		this.orderObject = orderObject;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "DH_ID")
	public Long getDhId() {
		return this.dhId;
	}

	public void setDhId(Long dhId) {
		this.dhId = dhId;
	}

	@Column(name = "PARTICIPANT_ID")
	public UUID getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(UUID participantId) {
		this.participantId = participantId;
	}

	@Column(name = "ORDER_OBJECT")
	public byte[] getOrderObject() {
		return this.orderObject;
	}

	public void setOrderObject(byte[] orderObject) {
		this.orderObject = orderObject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

}
