package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated May 26, 2015 6:09:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserSocietyDetails generated by hbm2java
 */
@Entity
@Table(name = "SOCIETIES")
public class Societies implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer societyId;
    private String societyCd;
    private String societyName;
    private Users createdBy;
    private Users updatedBy;
    private Date createdDate;
    private Date updatedDate;

    public Societies() {
    }

    public Societies(Integer societyId) {
        this.societyId = societyId;
    }

    public Societies(Integer societyId, Users createdBy, Users updatedBy,
            String societyCd, String societyName, Date createdDate,
            Date updatedDate) {
        this.societyId = societyId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.societyCd = societyCd;
        this.societyName = societyName;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    @Id
    @Column(name = "SOCIETY_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Integer getSocietyId() {
        return societyId;
    }

    public void setSocietyId(Integer societyId) {
        this.societyId = societyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATED_BY")
    public Users getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Users createdBy) {
        this.createdBy = createdBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPDATED_BY")
    public Users getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Users updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Column(name = "SOCIETY_CD", length = 14)
    public String getSocietyCd() {
        return societyCd;
    }

    public void setSocietyCd(String societyCd) {
        this.societyCd = societyCd;
    }

    @Column(name = "SOCIETY_NAME", length = 1000)
    public String getSocietyName() {
        return societyName;
    }

    public void setSocietyName(String societyName) {
        this.societyName = societyName;
    }

    @Column(name = "CREATED_DATE")
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "UPDATED_DATE")
    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

}
