package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 24, 2015 5:21:06 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Societies generated by hbm2java
 */
@Entity
@Table(name = "societies", catalog = "as2_app_db")
public class Societies implements java.io.Serializable {

	private String societyCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String societyName;
	private Date createdDate;
	private Date updatedDate;
	private Set<SocietyJournals> societyJournalses = new HashSet<SocietyJournals>(
			0);

	public Societies() {
	}

	public Societies(String societyCd) {
		this.societyCd = societyCd;
	}

	public Societies(String societyCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String societyName, Date createdDate,
			Date updatedDate, Set<SocietyJournals> societyJournalses) {
		this.societyCd = societyCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.societyName = societyName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.societyJournalses = societyJournalses;
	}

	@Id
	@Column(name = "SOCIETY_CD", unique = true, nullable = false, length = 15)
	public String getSocietyCd() {
		return this.societyCd;
	}

	public void setSocietyCd(String societyCd) {
		this.societyCd = societyCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "SOCIETY_NAME", length = 250)
	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "societies")
	public Set<SocietyJournals> getSocietyJournalses() {
		return this.societyJournalses;
	}

	public void setSocietyJournalses(Set<SocietyJournals> societyJournalses) {
		this.societyJournalses = societyJournalses;
	}

}
