package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jul 8, 2015 3:59:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SocietyJournals generated by hbm2java
 */
@Entity
@Table(name = "SOCIETY_JOURNALS")
public class SocietyJournals implements java.io.Serializable {

	private Integer societyJournalId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Products products;
	private Societies societies;
	private Date createdDate;
	private Date updatedDate;

	public SocietyJournals() {
	}

	public SocietyJournals(Integer societyJournalId) {
		this.societyJournalId = societyJournalId;
	}

	public SocietyJournals(Integer societyJournalId, Users usersByCreatedBy,
			Users usersByUpdatedBy, Products products, Societies societies,
			Date createdDate, Date updatedDate) {
		this.societyJournalId = societyJournalId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.products = products;
		this.societies = societies;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "SOCIETY_JOURNAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getSocietyJournalId() {
		return this.societyJournalId;
	}

	public void setSocietyJournalId(Integer societyJournalId) {
		this.societyJournalId = societyJournalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DH_ID")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOCIETY_CD")
	public Societies getSocieties() {
		return this.societies;
	}

	public void setSocieties(Societies societies) {
		this.societies = societies;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
