package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Societies generated by hbm2java
 */
public class Societies implements java.io.Serializable {

	private String societyCd;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String societyName;
	private Date createdDate;
	private Date updatedDate;
	private Set<SocietyJournals> societyJournalses = new HashSet<SocietyJournals>(
			0);

	public Societies() {
	}

	public Societies(String societyCd) {
		this.societyCd = societyCd;
	}

	public Societies(String societyCd, Users usersByCreatedBy,
			Users usersByUpdatedBy, String societyName, Date createdDate,
			Date updatedDate, Set<SocietyJournals> societyJournalses) {
		this.societyCd = societyCd;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.societyName = societyName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.societyJournalses = societyJournalses;
	}

	public String getSocietyCd() {
		return this.societyCd;
	}

	public void setSocietyCd(String societyCd) {
		this.societyCd = societyCd;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public Set<SocietyJournals> getSocietyJournalses() {
		return this.societyJournalses;
	}

	public void setSocietyJournalses(Set<SocietyJournals> societyJournalses) {
		this.societyJournalses = societyJournalses;
	}

}
