package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 16, 2015 3:47:59 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubOwnershipTypes generated by hbm2java
 */
@Entity
@Table(name = "sub_ownership_types", catalog = "as2_app_db")
public class SubOwnershipTypes implements java.io.Serializable {

	private String subTypeCd;
	private OwnershipTypes ownershipTypes;
	private String subTypeName;
	private Date createdDate;
	private byte[] createdBy;
	private Date updatedDate;
	private byte[] updatedBy;

	public SubOwnershipTypes() {
	}

	public SubOwnershipTypes(String subTypeCd) {
		this.subTypeCd = subTypeCd;
	}

	public SubOwnershipTypes(String subTypeCd, OwnershipTypes ownershipTypes,
			String subTypeName, Date createdDate, byte[] createdBy,
			Date updatedDate, byte[] updatedBy) {
		this.subTypeCd = subTypeCd;
		this.ownershipTypes = ownershipTypes;
		this.subTypeName = subTypeName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "SUB_TYPE_CD", unique = true, nullable = false, length = 50)
	public String getSubTypeCd() {
		return this.subTypeCd;
	}

	public void setSubTypeCd(String subTypeCd) {
		this.subTypeCd = subTypeCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPE_CD")
	public OwnershipTypes getOwnershipTypes() {
		return this.ownershipTypes;
	}

	public void setOwnershipTypes(OwnershipTypes ownershipTypes) {
		this.ownershipTypes = ownershipTypes;
	}

	@Column(name = "SUB_TYPE_NAME", length = 250)
	public String getSubTypeName() {
		return this.subTypeName;
	}

	public void setSubTypeName(String subTypeName) {
		this.subTypeName = subTypeName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

}
