package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 22, 2015 4:46:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubOwnershipTypes generated by hbm2java
 */
@Entity
@Table(name = "sub_ownership_types", catalog = "as2_app_db")
public class SubOwnershipTypes implements java.io.Serializable {

	private String subTypeCd;
	private String subTypeName;
	private String ownershipTypeCd;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public SubOwnershipTypes() {
	}

	public SubOwnershipTypes(String subTypeCd) {
		this.subTypeCd = subTypeCd;
	}

	public SubOwnershipTypes(String subTypeCd, String subTypeName,
			String ownershipTypeCd, Date createdDate, Long createdBy,
			Date updatedDate, Long updatedBy) {
		this.subTypeCd = subTypeCd;
		this.subTypeName = subTypeName;
		this.ownershipTypeCd = ownershipTypeCd;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "SUB_TYPE_CD", unique = true, nullable = false, length = 50)
	public String getSubTypeCd() {
		return this.subTypeCd;
	}

	public void setSubTypeCd(String subTypeCd) {
		this.subTypeCd = subTypeCd;
	}

	@Column(name = "SUB_TYPE_NAME", length = 250)
	public String getSubTypeName() {
		return this.subTypeName;
	}

	public void setSubTypeName(String subTypeName) {
		this.subTypeName = subTypeName;
	}

	@Column(name = "OWNERSHIP_TYPE_CD", length = 25)
	public String getOwnershipTypeCd() {
		return this.ownershipTypeCd;
	}

	public void setOwnershipTypeCd(String ownershipTypeCd) {
		this.ownershipTypeCd = ownershipTypeCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
