package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private UserRolesId id;
	private Roles roles;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private Users usersByUserId;
	private Date createdDate;
	private Date updatedDate;

	public UserRoles() {
	}

	public UserRoles(UserRolesId id, Roles roles, Users usersByUserId) {
		this.id = id;
		this.roles = roles;
		this.usersByUserId = usersByUserId;
	}

	public UserRoles(UserRolesId id, Roles roles, Users usersByCreatedBy,
			Users usersByUpdatedBy, Users usersByUserId, Date createdDate,
			Date updatedDate) {
		this.id = id;
		this.roles = roles;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.usersByUserId = usersByUserId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public UserRolesId getId() {
		return this.id;
	}

	public void setId(UserRolesId id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public Users getUsersByUserId() {
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId) {
		this.usersByUserId = usersByUserId;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
