package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UserAreaOfInterest generated by hbm2java
 */
public class UserAreaOfInterest implements java.io.Serializable {

	private UserAreaOfInterestId id;
	private AreaOfInterest areaOfInterest;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private UserProfile userProfile;
	private Date createdDate;
	private Date updatedDate;

	public UserAreaOfInterest() {
	}

	public UserAreaOfInterest(UserAreaOfInterestId id,
			AreaOfInterest areaOfInterest, UserProfile userProfile) {
		this.id = id;
		this.areaOfInterest = areaOfInterest;
		this.userProfile = userProfile;
	}

	public UserAreaOfInterest(UserAreaOfInterestId id,
			AreaOfInterest areaOfInterest, Users usersByCreatedBy,
			Users usersByUpdatedBy, UserProfile userProfile, Date createdDate,
			Date updatedDate) {
		this.id = id;
		this.areaOfInterest = areaOfInterest;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.userProfile = userProfile;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public UserAreaOfInterestId getId() {
		return this.id;
	}

	public void setId(UserAreaOfInterestId id) {
		this.id = id;
	}

	public AreaOfInterest getAreaOfInterest() {
		return this.areaOfInterest;
	}

	public void setAreaOfInterest(AreaOfInterest areaOfInterest) {
		this.areaOfInterest = areaOfInterest;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
