package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UserFunderGrants generated by hbm2java
 */
public class UserFunderGrants implements java.io.Serializable {

	private Long funderGrantId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private UserFunders userFunders;
	private String grantNum;
	private Date createdDate;
	private Date updatedDate;

	public UserFunderGrants() {
	}

	public UserFunderGrants(Users usersByCreatedBy, Users usersByUpdatedBy,
			UserFunders userFunders, String grantNum, Date createdDate,
			Date updatedDate) {
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.userFunders = userFunders;
		this.grantNum = grantNum;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public Long getFunderGrantId() {
		return this.funderGrantId;
	}

	public void setFunderGrantId(Long funderGrantId) {
		this.funderGrantId = funderGrantId;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public UserFunders getUserFunders() {
		return this.userFunders;
	}

	public void setUserFunders(UserFunders userFunders) {
		this.userFunders = userFunders;
	}

	public String getGrantNum() {
		return this.grantNum;
	}

	public void setGrantNum(String grantNum) {
		this.grantNum = grantNum;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
