package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 16, 2015 3:47:59 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserFunders generated by hbm2java
 */
@Entity
@Table(name = "user_funders", catalog = "as2_app_db")
public class UserFunders implements java.io.Serializable {

	private long userFunderId;
	private byte[] participantId;
	private String funderDoi;
	private String funderName;
	private Date createdDate;
	private byte[] createdBy;
	private Date updatedDate;
	private byte[] updatedBy;
	private Set<UserFunderGrants> userFunderGrantses = new HashSet<UserFunderGrants>(
			0);

	public UserFunders() {
	}

	public UserFunders(long userFunderId) {
		this.userFunderId = userFunderId;
	}

	public UserFunders(long userFunderId, byte[] participantId,
			String funderDoi, String funderName, Date createdDate,
			byte[] createdBy, Date updatedDate, byte[] updatedBy,
			Set<UserFunderGrants> userFunderGrantses) {
		this.userFunderId = userFunderId;
		this.participantId = participantId;
		this.funderDoi = funderDoi;
		this.funderName = funderName;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.userFunderGrantses = userFunderGrantses;
	}

	@Id
	@Column(name = "USER_FUNDER_ID", unique = true, nullable = false)
	public long getUserFunderId() {
		return this.userFunderId;
	}

	public void setUserFunderId(long userFunderId) {
		this.userFunderId = userFunderId;
	}

	@Column(name = "PARTICIPANT_ID")
	public byte[] getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(byte[] participantId) {
		this.participantId = participantId;
	}

	@Column(name = "FUNDER_DOI", length = 50)
	public String getFunderDoi() {
		return this.funderDoi;
	}

	public void setFunderDoi(String funderDoi) {
		this.funderDoi = funderDoi;
	}

	@Column(name = "FUNDER_NAME", length = 250)
	public String getFunderName() {
		return this.funderName;
	}

	public void setFunderName(String funderName) {
		this.funderName = funderName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userFunders")
	public Set<UserFunderGrants> getUserFunderGrantses() {
		return this.userFunderGrantses;
	}

	public void setUserFunderGrantses(Set<UserFunderGrants> userFunderGrantses) {
		this.userFunderGrantses = userFunderGrantses;
	}

}
