package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

/**
 * UserPreferredJournalsId generated by hbm2java
 */
public class UserPreferredJournalsId implements java.io.Serializable {

	private long userId;
	private long dhId;

	public UserPreferredJournalsId() {
	}

	public UserPreferredJournalsId(long userId, long dhId) {
		this.userId = userId;
		this.dhId = dhId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getDhId() {
		return this.dhId;
	}

	public void setDhId(long dhId) {
		this.dhId = dhId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserPreferredJournalsId))
			return false;
		UserPreferredJournalsId castOther = (UserPreferredJournalsId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getDhId() == castOther.getDhId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getDhId();
		return result;
	}

}
