package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 22, 2015 4:46:21 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserFunderGrants generated by hbm2java
 */
@Entity
@Table(name = "user_funder_grants", catalog = "as2_app_db")
public class UserFunderGrants implements java.io.Serializable {

	private Long funderGrantId;
	private Long userFunderId;
	private String grantNum;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public UserFunderGrants() {
	}

	public UserFunderGrants(Long userFunderId, String grantNum,
			Date createdDate, Long createdBy, Date updatedDate, Long updatedBy) {
		this.userFunderId = userFunderId;
		this.grantNum = grantNum;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FUNDER_GRANT_ID", unique = true, nullable = false)
	public Long getFunderGrantId() {
		return this.funderGrantId;
	}

	public void setFunderGrantId(Long funderGrantId) {
		this.funderGrantId = funderGrantId;
	}

	@Column(name = "USER_FUNDER_ID")
	public Long getUserFunderId() {
		return this.userFunderId;
	}

	public void setUserFunderId(Long userFunderId) {
		this.userFunderId = userFunderId;
	}

	@Column(name = "GRANT_NUM", length = 100)
	public String getGrantNum() {
		return this.grantNum;
	}

	public void setGrantNum(String grantNum) {
		this.grantNum = grantNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
