package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

/**
 * UserProfileAttribVisibleId generated by hbm2java
 */
public class UserProfileAttribVisibleId implements java.io.Serializable {

	private long userId;
	private String profileAttribCd;

	public UserProfileAttribVisibleId() {
	}

	public UserProfileAttribVisibleId(long userId, String profileAttribCd) {
		this.userId = userId;
		this.profileAttribCd = profileAttribCd;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getProfileAttribCd() {
		return this.profileAttribCd;
	}

	public void setProfileAttribCd(String profileAttribCd) {
		this.profileAttribCd = profileAttribCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProfileAttribVisibleId))
			return false;
		UserProfileAttribVisibleId castOther = (UserProfileAttribVisibleId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getProfileAttribCd() == castOther
						.getProfileAttribCd()) || (this.getProfileAttribCd() != null
						&& castOther.getProfileAttribCd() != null && this
						.getProfileAttribCd().equals(
								castOther.getProfileAttribCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getProfileAttribCd() == null ? 0 : this.getProfileAttribCd()
						.hashCode());
		return result;
	}

}
