package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 28, 2015 6:59:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UserProfileAttribVisible generated by hbm2java
 */
public class UserProfileAttribVisible implements java.io.Serializable {

	private UserProfileAttribVisibleId id;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private UserProfile userProfile;
	private ProfileAttributeList profileAttributeList;
	private Character profileVisibilityFlg;
	private Date createdDate;
	private Date updatedDate;

	public UserProfileAttribVisible() {
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id,
			UserProfile userProfile, ProfileAttributeList profileAttributeList) {
		this.id = id;
		this.userProfile = userProfile;
		this.profileAttributeList = profileAttributeList;
	}

	public UserProfileAttribVisible(UserProfileAttribVisibleId id,
			Users usersByCreatedBy, Users usersByUpdatedBy,
			UserProfile userProfile, ProfileAttributeList profileAttributeList,
			Character profileVisibilityFlg, Date createdDate, Date updatedDate) {
		this.id = id;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.userProfile = userProfile;
		this.profileAttributeList = profileAttributeList;
		this.profileVisibilityFlg = profileVisibilityFlg;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	public UserProfileAttribVisibleId getId() {
		return this.id;
	}

	public void setId(UserProfileAttribVisibleId id) {
		this.id = id;
	}

	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public ProfileAttributeList getProfileAttributeList() {
		return this.profileAttributeList;
	}

	public void setProfileAttributeList(
			ProfileAttributeList profileAttributeList) {
		this.profileAttributeList = profileAttributeList;
	}

	public Character getProfileVisibilityFlg() {
		return this.profileVisibilityFlg;
	}

	public void setProfileVisibilityFlg(Character profileVisibilityFlg) {
		this.profileVisibilityFlg = profileVisibilityFlg;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
