package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSocietyDetails generated by hbm2java
 */
@Entity
@Table(name = "user_society_details", catalog = "as2_app_db")
public class UserSocietyDetails implements java.io.Serializable {

	private Long userSocietyId;
	private Societies societies;
	private UUID participantId;
	private String societyName;
	private String membershipNo;
	private String promoCode;
	private Date startDt;
	private Date endDt;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;

	public UserSocietyDetails() {
	}

	public UserSocietyDetails(Societies societies, UUID participantId,
			String societyName, String membershipNo, String promoCode,
			Date startDt, Date endDt, Date createdDate, UUID createdBy,
			Date updatedDate, UUID updatedBy) {
		this.societies = societies;
		this.participantId = participantId;
		this.societyName = societyName;
		this.membershipNo = membershipNo;
		this.promoCode = promoCode;
		this.startDt = startDt;
		this.endDt = endDt;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_SOCIETY_ID", unique = true, nullable = false)
	public Long getUserSocietyId() {
		return this.userSocietyId;
	}

	public void setUserSocietyId(Long userSocietyId) {
		this.userSocietyId = userSocietyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOCIETY_CD")
	public Societies getSocieties() {
		return this.societies;
	}

	public void setSocieties(Societies societies) {
		this.societies = societies;
	}

	@Column(name = "PARTICIPANT_ID")
	public UUID getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(UUID participantId) {
		this.participantId = participantId;
	}

	@Column(name = "SOCIETY_NAME", length = 500)
	public String getSocietyName() {
		return this.societyName;
	}

	public void setSocietyName(String societyName) {
		this.societyName = societyName;
	}

	@Column(name = "MEMBERSHIP_NO", length = 50)
	public String getMembershipNo() {
		return this.membershipNo;
	}

	public void setMembershipNo(String membershipNo) {
		this.membershipNo = membershipNo;
	}

	@Column(name = "PROMO_CODE", length = 50)
	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DT", length = 19)
	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DT", length = 19)
	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

}
