package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Oct 19, 2015 4:16:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAffiliations generated by hbm2java
 */
@Entity
@Table(name = "user_affiliations", catalog = "as2_app_db")
public class UserAffiliations implements java.io.Serializable {

	private Long affiliationId;
	private UUID participantId;
	private String institutionCd;
	private String institutionName;
	private String departmentCd;
	private String departmentName;
	private String townOrCityName;
	private String stateOrProvinceName;
	private String countryCd;
	private Date startDt;
	private Date endDt;
	private Date createdDate;
	private UUID createdBy;
	private Date updatedDate;
	private UUID updatedBy;

	public UserAffiliations() {
	}

	public UserAffiliations(UUID participantId, String institutionCd,
			String institutionName, String departmentCd, String departmentName,
			String townOrCityName, String stateOrProvinceName,
			String countryCd, Date startDt, Date endDt, Date createdDate,
			UUID createdBy, Date updatedDate, UUID updatedBy) {
		this.participantId = participantId;
		this.institutionCd = institutionCd;
		this.institutionName = institutionName;
		this.departmentCd = departmentCd;
		this.departmentName = departmentName;
		this.townOrCityName = townOrCityName;
		this.stateOrProvinceName = stateOrProvinceName;
		this.countryCd = countryCd;
		this.startDt = startDt;
		this.endDt = endDt;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AFFILIATION_ID", unique = true, nullable = false)
	public Long getAffiliationId() {
		return this.affiliationId;
	}

	public void setAffiliationId(Long affiliationId) {
		this.affiliationId = affiliationId;
	}

	@Column(name = "PARTICIPANT_ID")
	public UUID getParticipantId() {
		return this.participantId;
	}

	public void setParticipantId(UUID participantId) {
		this.participantId = participantId;
	}

	@Column(name = "INSTITUTION_CD", length = 10)
	public String getInstitutionCd() {
		return this.institutionCd;
	}

	public void setInstitutionCd(String institutionCd) {
		this.institutionCd = institutionCd;
	}

	@Column(name = "INSTITUTION_NAME", length = 100)
	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	@Column(name = "DEPARTMENT_CD", length = 10)
	public String getDepartmentCd() {
		return this.departmentCd;
	}

	public void setDepartmentCd(String departmentCd) {
		this.departmentCd = departmentCd;
	}

	@Column(name = "DEPARTMENT_NAME", length = 100)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "TOWN_OR_CITY_NAME", length = 200)
	public String getTownOrCityName() {
		return this.townOrCityName;
	}

	public void setTownOrCityName(String townOrCityName) {
		this.townOrCityName = townOrCityName;
	}

	@Column(name = "STATE_OR_PROVINCE_NAME", length = 200)
	public String getStateOrProvinceName() {
		return this.stateOrProvinceName;
	}

	public void setStateOrProvinceName(String stateOrProvinceName) {
		this.stateOrProvinceName = stateOrProvinceName;
	}

	@Column(name = "COUNTRY_CD", length = 15)
	public String getCountryCd() {
		return this.countryCd;
	}

	public void setCountryCd(String countryCd) {
		this.countryCd = countryCd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DT", length = 19)
	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DT", length = 19)
	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public UUID getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(UUID createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public UUID getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(UUID updatedBy) {
		this.updatedBy = updatedBy;
	}

}
