package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Jul 8, 2015 3:59:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WpgResponseDetails generated by hbm2java
 */
@Entity
@Table(name = "WPG_RESPONSE_DETAILS")
public class WpgResponseDetails implements java.io.Serializable {

	private Integer wpgLogId;
	private Users usersByCreatedBy;
	private Users usersByUpdatedBy;
	private String operation;
	private Integer returnCode;
	private String returnMessage;
	private Integer vendorId;
	private Integer transId;
	private String merchantResponse;
	private Integer merchantId;
	private Character cscResult;
	private Character avsAddressResult;
	private Character avsPostResult;
	private String token;
	private Character acquirerId;
	private String acquirerBank;
	private Character bankId;
	private String bankName;
	private String maskedCardNumber;
	private Integer cardExpiry;
	private Date transTimestamp;
	private String security;
	private Date createdDate;
	private Date updatedDate;

	public WpgResponseDetails() {
	}

	public WpgResponseDetails(Integer wpgLogId) {
		this.wpgLogId = wpgLogId;
	}

	public WpgResponseDetails(Integer wpgLogId, Users usersByCreatedBy,
			Users usersByUpdatedBy, String operation, Integer returnCode,
			String returnMessage, Integer vendorId, Integer transId,
			String merchantResponse, Integer merchantId, Character cscResult,
			Character avsAddressResult, Character avsPostResult, String token,
			Character acquirerId, String acquirerBank, Character bankId,
			String bankName, String maskedCardNumber, Integer cardExpiry,
			Date transTimestamp, String security, Date createdDate,
			Date updatedDate) {
		this.wpgLogId = wpgLogId;
		this.usersByCreatedBy = usersByCreatedBy;
		this.usersByUpdatedBy = usersByUpdatedBy;
		this.operation = operation;
		this.returnCode = returnCode;
		this.returnMessage = returnMessage;
		this.vendorId = vendorId;
		this.transId = transId;
		this.merchantResponse = merchantResponse;
		this.merchantId = merchantId;
		this.cscResult = cscResult;
		this.avsAddressResult = avsAddressResult;
		this.avsPostResult = avsPostResult;
		this.token = token;
		this.acquirerId = acquirerId;
		this.acquirerBank = acquirerBank;
		this.bankId = bankId;
		this.bankName = bankName;
		this.maskedCardNumber = maskedCardNumber;
		this.cardExpiry = cardExpiry;
		this.transTimestamp = transTimestamp;
		this.security = security;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "WPG_LOG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getWpgLogId() {
		return this.wpgLogId;
	}

	public void setWpgLogId(Integer wpgLogId) {
		this.wpgLogId = wpgLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public Users getUsersByCreatedBy() {
		return this.usersByCreatedBy;
	}

	public void setUsersByCreatedBy(Users usersByCreatedBy) {
		this.usersByCreatedBy = usersByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UPDATED_BY")
	public Users getUsersByUpdatedBy() {
		return this.usersByUpdatedBy;
	}

	public void setUsersByUpdatedBy(Users usersByUpdatedBy) {
		this.usersByUpdatedBy = usersByUpdatedBy;
	}

	@Column(name = "OPERATION", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "RETURN_CODE", precision = 22, scale = 0)
	public Integer getReturnCode() {
		return this.returnCode;
	}

	public void setReturnCode(Integer returnCode) {
		this.returnCode = returnCode;
	}

	@Column(name = "RETURN_MESSAGE", length = 100)
	public String getReturnMessage() {
		return this.returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	@Column(name = "VENDOR_ID", precision = 22, scale = 0)
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "TRANS_ID", precision = 22, scale = 0)
	public Integer getTransId() {
		return this.transId;
	}

	public void setTransId(Integer transId) {
		this.transId = transId;
	}

	@Column(name = "MERCHANT_RESPONSE", length = 100)
	public String getMerchantResponse() {
		return this.merchantResponse;
	}

	public void setMerchantResponse(String merchantResponse) {
		this.merchantResponse = merchantResponse;
	}

	@Column(name = "MERCHANT_ID", precision = 22, scale = 0)
	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "CSC_RESULT", length = 1)
	public Character getCscResult() {
		return this.cscResult;
	}

	public void setCscResult(Character cscResult) {
		this.cscResult = cscResult;
	}

	@Column(name = "AVS_ADDRESS_RESULT", length = 1)
	public Character getAvsAddressResult() {
		return this.avsAddressResult;
	}

	public void setAvsAddressResult(Character avsAddressResult) {
		this.avsAddressResult = avsAddressResult;
	}

	@Column(name = "AVS_POST_RESULT", length = 1)
	public Character getAvsPostResult() {
		return this.avsPostResult;
	}

	public void setAvsPostResult(Character avsPostResult) {
		this.avsPostResult = avsPostResult;
	}

	@Column(name = "TOKEN", length = 25)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "ACQUIRER_ID", length = 1)
	public Character getAcquirerId() {
		return this.acquirerId;
	}

	public void setAcquirerId(Character acquirerId) {
		this.acquirerId = acquirerId;
	}

	@Column(name = "ACQUIRER_BANK", length = 25)
	public String getAcquirerBank() {
		return this.acquirerBank;
	}

	public void setAcquirerBank(String acquirerBank) {
		this.acquirerBank = acquirerBank;
	}

	@Column(name = "BANK_ID", length = 1)
	public Character getBankId() {
		return this.bankId;
	}

	public void setBankId(Character bankId) {
		this.bankId = bankId;
	}

	@Column(name = "BANK_NAME", length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "MASKED_CARD_NUMBER", length = 25)
	public String getMaskedCardNumber() {
		return this.maskedCardNumber;
	}

	public void setMaskedCardNumber(String maskedCardNumber) {
		this.maskedCardNumber = maskedCardNumber;
	}

	@Column(name = "CARD_EXPIRY", precision = 22, scale = 0)
	public Integer getCardExpiry() {
		return this.cardExpiry;
	}

	public void setCardExpiry(Integer cardExpiry) {
		this.cardExpiry = cardExpiry;
	}

	@Column(name = "TRANS_TIMESTAMP")
	public Date getTransTimestamp() {
		return this.transTimestamp;
	}

	public void setTransTimestamp(Date transTimestamp) {
		this.transTimestamp = transTimestamp;
	}

	@Column(name = "SECURITY", length = 50)
	public String getSecurity() {
		return this.security;
	}

	public void setSecurity(String security) {
		this.security = security;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
