package com.wiley.gr.ace.authorservices.persistence.entity;

// Generated Sep 29, 2015 12:48:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WpgResponseDetails generated by hbm2java
 */
@Entity
@Table(name = "wpg_response_details", catalog = "as2_app_db")
public class WpgResponseDetails implements java.io.Serializable {

	private Long wpgLogId;
	private String operation;
	private Long returnCode;
	private String returnMessage;
	private Long vendorId;
	private Long transId;
	private String merchantResponse;
	private Long merchantId;
	private Boolean cscResult;
	private Boolean avsAddressResult;
	private Boolean avsPostResult;
	private String token;
	private Boolean acquirerId;
	private String acquirerName;
	private Boolean bankId;
	private String bankName;
	private String maskedCardNumber;
	private Long cardExpiry;
	private Date transTimestamp;
	private String security;
	private Date createdDate;
	private Long createdBy;
	private Date updatedDate;
	private Long updatedBy;

	public WpgResponseDetails() {
	}

	public WpgResponseDetails(String operation, Long returnCode,
			String returnMessage, Long vendorId, Long transId,
			String merchantResponse, Long merchantId, Boolean cscResult,
			Boolean avsAddressResult, Boolean avsPostResult, String token,
			Boolean acquirerId, String acquirerName, Boolean bankId,
			String bankName, String maskedCardNumber, Long cardExpiry,
			Date transTimestamp, String security, Date createdDate,
			Long createdBy, Date updatedDate, Long updatedBy) {
		this.operation = operation;
		this.returnCode = returnCode;
		this.returnMessage = returnMessage;
		this.vendorId = vendorId;
		this.transId = transId;
		this.merchantResponse = merchantResponse;
		this.merchantId = merchantId;
		this.cscResult = cscResult;
		this.avsAddressResult = avsAddressResult;
		this.avsPostResult = avsPostResult;
		this.token = token;
		this.acquirerId = acquirerId;
		this.acquirerName = acquirerName;
		this.bankId = bankId;
		this.bankName = bankName;
		this.maskedCardNumber = maskedCardNumber;
		this.cardExpiry = cardExpiry;
		this.transTimestamp = transTimestamp;
		this.security = security;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "WPG_LOG_ID", unique = true, nullable = false)
	public Long getWpgLogId() {
		return this.wpgLogId;
	}

	public void setWpgLogId(Long wpgLogId) {
		this.wpgLogId = wpgLogId;
	}

	@Column(name = "OPERATION", length = 50)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "RETURN_CODE")
	public Long getReturnCode() {
		return this.returnCode;
	}

	public void setReturnCode(Long returnCode) {
		this.returnCode = returnCode;
	}

	@Column(name = "RETURN_MESSAGE", length = 100)
	public String getReturnMessage() {
		return this.returnMessage;
	}

	public void setReturnMessage(String returnMessage) {
		this.returnMessage = returnMessage;
	}

	@Column(name = "VENDOR_ID")
	public Long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "TRANS_ID")
	public Long getTransId() {
		return this.transId;
	}

	public void setTransId(Long transId) {
		this.transId = transId;
	}

	@Column(name = "MERCHANT_RESPONSE", length = 100)
	public String getMerchantResponse() {
		return this.merchantResponse;
	}

	public void setMerchantResponse(String merchantResponse) {
		this.merchantResponse = merchantResponse;
	}

	@Column(name = "MERCHANT_ID")
	public Long getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Long merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "CSC_RESULT", length = 1)
	public Boolean getCscResult() {
		return this.cscResult;
	}

	public void setCscResult(Boolean cscResult) {
		this.cscResult = cscResult;
	}

	@Column(name = "AVS_ADDRESS_RESULT", length = 1)
	public Boolean getAvsAddressResult() {
		return this.avsAddressResult;
	}

	public void setAvsAddressResult(Boolean avsAddressResult) {
		this.avsAddressResult = avsAddressResult;
	}

	@Column(name = "AVS_POST_RESULT", length = 1)
	public Boolean getAvsPostResult() {
		return this.avsPostResult;
	}

	public void setAvsPostResult(Boolean avsPostResult) {
		this.avsPostResult = avsPostResult;
	}

	@Column(name = "TOKEN", length = 25)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "ACQUIRER_ID", length = 1)
	public Boolean getAcquirerId() {
		return this.acquirerId;
	}

	public void setAcquirerId(Boolean acquirerId) {
		this.acquirerId = acquirerId;
	}

	@Column(name = "ACQUIRER_NAME", length = 25)
	public String getAcquirerName() {
		return this.acquirerName;
	}

	public void setAcquirerName(String acquirerName) {
		this.acquirerName = acquirerName;
	}

	@Column(name = "BANK_ID", length = 1)
	public Boolean getBankId() {
		return this.bankId;
	}

	public void setBankId(Boolean bankId) {
		this.bankId = bankId;
	}

	@Column(name = "BANK_NAME", length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "MASKED_CARD_NUMBER", length = 25)
	public String getMaskedCardNumber() {
		return this.maskedCardNumber;
	}

	public void setMaskedCardNumber(String maskedCardNumber) {
		this.maskedCardNumber = maskedCardNumber;
	}

	@Column(name = "CARD_EXPIRY")
	public Long getCardExpiry() {
		return this.cardExpiry;
	}

	public void setCardExpiry(Long cardExpiry) {
		this.cardExpiry = cardExpiry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANS_TIMESTAMP", length = 19)
	public Date getTransTimestamp() {
		return this.transTimestamp;
	}

	public void setTransTimestamp(Date transTimestamp) {
		this.transTimestamp = transTimestamp;
	}

	@Column(name = "SECURITY", length = 50)
	public String getSecurity() {
		return this.security;
	}

	public void setSecurity(String security) {
		this.security = security;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
